### ISSUE TITLE
ChunkedEncodingError on submitting workflow to gcloud server (but workflow runs successfully)

### ISSUE THREAD

**Issue by isaacliao** [StanfordBioinformatics/loom#110]
Seen in be0e7137d72d92a1a4e629987fd7b4cf32529bc8. Example output below. However, workflow runs fine, workers are created, and final output is uploaded to Google Storage.

```
$ loom run hello_world.json hello=hello.txt world=world.txt
Importing workflow from file:///Users/iliao/venvs/loom/loom/doc/examples/hello_world/hello_world.json...
...finished importing workflow hello_world@8d83c840eab5eed081d3bd0138a792d849b84a677d54820678ba24afac66e1ad
Importing file from file:///Users/iliao/venvs/loom/loom/doc/examples/hello_world/hello.txt...
...to temporary destination gs://gbsc-gcp-project-scgs-dev-loom/loom_working_dir/tmp/f3727d8dcaa04d41b0c318ef9b7a9359...
...to final destination gs://gbsc-gcp-project-scgs-dev-loom/loom_working_dir/imported/20160627222406-b89c320f008442be90fd8e00d0c3ca08-hello.txt...
...finished importing file hello.txt@b89c320f008442be90fd8e00d0c3ca08
Importing file from file:///Users/iliao/venvs/loom/loom/doc/examples/hello_world/world.txt...
...to temporary destination gs://gbsc-gcp-project-scgs-dev-loom/loom_working_dir/tmp/ab96ad82167a404d96daf80ae942f4d3...
...to final destination gs://gbsc-gcp-project-scgs-dev-loom/loom_working_dir/imported/20160627222409-0669a576d18748858c4ff84266984ded-world.txt...
...finished importing file world.txt@0669a576d18748858c4ff84266984ded
Traceback (most recent call last):
  File "/Users/iliao/venvs/loom2/bin/loom", line 11, in <module>
sys.exit(main())
  File "/Users/iliao/venvs/loom2/lib/python2.7/site-packages/loom/client/main.py", line 72, in main
Main().run()
  File "/Users/iliao/venvs/loom2/lib/python2.7/site-packages/loom/client/main.py", line 68, in run
self.args.SubcommandClass(self.args).run()
  File "/Users/iliao/venvs/loom2/lib/python2.7/site-packages/loom/client/run.py", line 64, in run
'inputs': inputs
  File "/Users/iliao/venvs/loom2/lib/python2.7/site-packages/loom/common/objecthandler.py", line 161, in post_run_request
'run-requests/')
  File "/Users/iliao/venvs/loom2/lib/python2.7/site-packages/loom/common/objecthandler.py", line 53, in _post_object
return self._post(object_data, relative_url, raise_for_status=True).json()['object']
  File "/Users/iliao/venvs/loom2/lib/python2.7/site-packages/loom/common/objecthandler.py", line 19, in _post
return self._make_request_to_server(lambda: requests.post(url, data=json.dumps(data)), raise_for_status=raise_for_status)
  File "/Users/iliao/venvs/loom2/lib/python2.7/site-packages/loom/common/objecthandler.py", line 37, in _make_request_to_server
response = query_function()
  File "/Users/iliao/venvs/loom2/lib/python2.7/site-packages/loom/common/objecthandler.py", line 19, in <lambda>
return self._make_request_to_server(lambda: requests.post(url, data=json.dumps(data)), raise_for_status=raise_for_status)
  File "/Users/iliao/venvs/loom2/lib/python2.7/site-packages/requests/api.py", line 111, in post
return request('post', url, data=data, json=json, **kwargs)
  File "/Users/iliao/venvs/loom2/lib/python2.7/site-packages/requests/api.py", line 57, in request
return session.request(method=method, url=url, **kwargs)
  File "/Users/iliao/venvs/loom2/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
resp = self.send(prep, **send_kwargs)
  File "/Users/iliao/venvs/loom2/lib/python2.7/site-packages/requests/sessions.py", line 617, in send
r.content
  File "/Users/iliao/venvs/loom2/lib/python2.7/site-packages/requests/models.py", line 741, in content
self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/Users/iliao/venvs/loom2/lib/python2.7/site-packages/requests/models.py", line 667, in generate
raise ChunkedEncodingError(e)
requests.exceptions
.
ChunkedEncodingError
:
('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
```

**Comment by isaacliao** [comment]
Obsolete, haven't seen this error and models have been significantly refactored since.
