### ISSUE TITLE
Running "loom server start" before config should give helpful message

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#113]
(env) timba:loom nhammond$ loom server start
ERROR! The file /Users/nhammond/work/loom/loom/loom/common/gce.py is marked as executable, but failed to execute correctly. If this is not supposed to be an executable script, correct this with `chmod -x /Users/nhammond/work/loom/loom/loom/common/gce.py`.
Inventory script (/Users/nhammond/work/loom/loom/loom/common/gce.py) had an execution error: Traceback (most recent call last):
  File "/Users/nhammond/work/loom/loom/loom/common/gce.py", line 300, in <module>
    GceInventory()
  File "/Users/nhammond/work/loom/loom/loom/common/gce.py", line 111, in **init**
    self.driver = self.get_gce_driver()
  File "/Users/nhammond/work/loom/loom/loom/common/gce.py", line 187, in get_gce_driver
    gce = get_driver(Provider.GCE)(_args, *_kwargs)
  File "/Users/nhammond/work/loom/env/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py", line 1075, in **init**
    super(GCENodeDriver, self).**init**(user_id, key, **kwargs)
  File "/Users/nhammond/work/loom/env/lib/python2.7/site-packages/libcloud/common/base.py", line 1163, in **init**
    self.connection.connect()
  File "/Users/nhammond/work/loom/env/lib/python2.7/site-packages/libcloud/common/base.py", line 663, in connect
    connection = self.conn_classes[secure](**kwargs)
  File "/Users/nhammond/work/loom/env/lib/python2.7/site-packages/libcloud/httplib_ssl.py", line 224, in **init**
    self._setup_verify()
  File "/Users/nhammond/work/loom/env/lib/python2.7/site-packages/libcloud/httplib_ssl.py", line 245, in _setup_verify
    self._setup_ca_cert()
  File "/Users/nhammond/work/loom/env/lib/python2.7/site-packages/libcloud/httplib_ssl.py", line 268, in _setup_ca_cert
    libcloud.security.CA_CERTS_UNAVAILABLE_ERROR_MSG)
RuntimeError: No CA Certificates were found in CA_CERTS_PATH. For information on how to get required certificate files, please visit https://libcloud.readthedocs.org/en/latest/other/ssl-certificate-validation.html

/Users/nhammond/work/loom/loom/loom/common/gce.py:19: Error parsing host definition ''''': No closing quotation

**Comment by nhammond** [comment]
Obsolete with release 0.3.0. Removed "loom server set" and "loom server create".
