### ISSUE TITLE
Hide raw errors from "loom version" before loom server set or create

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#148]
Running "loom version" before any setup gives the error below. Running after "loom server set" but before "create" gives the same error.

(env) LAP14728m:loom s0198839$ loom version
Traceback (most recent call last):
  File "/Users/s0198839/work/loom/env/bin/loom", line 9, in <module>
    load_entry_point('loomengine', 'console_scripts', 'loom')()
  File "/Users/s0198839/work/loom/loom/loom/client/main.py", line 72, in main
    Main().run()
  File "/Users/s0198839/work/loom/loom/loom/client/main.py", line 68, in run
    self.args.SubcommandClass(self.args).run()
  File "/Users/s0198839/work/loom/loom/loom/client/version.py", line 19, in **init**
    self.objecthandler = self._get_objecthandler()
  File "/Users/s0198839/work/loom/loom/loom/client/version.py", line 22, in _get_objecthandler
    master_url = get_server_url()
  File "/Users/s0198839/work/loom/loom/loom/client/common.py", line 100, in get_server_url
    raise Exception("Could not open server deploy settings. Do you need to run \"loom server create\" first?")
Exception: Could not open server deploy settings. Do you need to run "loom server create" first?

**Comment by nhammond** [comment]
Fixed in 0.3.0. No more set and create.
