### ISSUE TITLE
loom export error

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#150]
(env) LAP14728m:loom s0198839$ loom export file x
Traceback (most recent call last):
  File "/Users/s0198839/work/loom/env/bin/loom", line 9, in <module>
    load_entry_point('loomengine', 'console_scripts', 'loom')()
  File "/Users/s0198839/work/loom/loom/loom/client/main.py", line 72, in main
    Main().run()
  File "/Users/s0198839/work/loom/loom/loom/client/main.py", line 68, in run
    self.args.SubcommandClass(self.args).run()
  File "/Users/s0198839/work/loom/loom/loom/client/exporter.py", line 138, in run
    self.args.SubSubcommandClass(self.args).run()
  File "/Users/s0198839/work/loom/loom/loom/client/exporter.py", line 28, in __init__
    master_url = get_server_url_for_client()
NameError: global name 'get_server_url_for_client' is not defined

**Comment by nhammond** [comment]
This is fixed. File download of existing file works, and non-existing file produces a relevant error.
