### ISSUE TITLE
Give a message for invalid settings file

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#152]
(env) LAP14728m:loom s0198839$ loom server create --settings ~/scratch.txt
Traceback (most recent call last):
  File "/Users/s0198839/work/loom/env/bin/loom", line 9, in <module>
    load_entry_point('loomengine', 'console_scripts', 'loom')()
  File "/Users/s0198839/work/loom/loom/loom/client/main.py", line 72, in main
    Main().run()
  File "/Users/s0198839/work/loom/loom/loom/client/main.py", line 68, in run
    self.args.SubcommandClass(self.args).run()
  File "/Users/s0198839/work/loom/loom/loom/client/server.py", line 375, in create
    self.settings_manager.create_deploy_settings_file(self.args.settings)
  File "/Users/s0198839/work/loom/loom/loom/client/settings_manager.py", line 76, in create_deploy_settings_file
    self.create_deploy_settings(user_settings_file=user_settings_file)
  File "/Users/s0198839/work/loom/loom/loom/client/settings_manager.py", line 45, in create_deploy_settings
    self.load_settings_from_file(settings_file=user_settings_file, section=server_type)
  File "/Users/s0198839/work/loom/loom/loom/client/settings_manager.py", line 97, in load_settings_from_file
    raise SettingsError("Failed to open settings file %s: %s" % (settings_file, e))
loom.client.settings_manager.SettingsError: Failed to open settings file /Users/s0198839/scratch.txt: File contains no section headers.
file: /Users/s0198839/scratch.txt, line: 1
'xx\n'

**Comment by nhammond** [comment]
Fixed with release 0.3.0. No section header required. (Incidentally, no error is raised if an ini-style section header is used.)
