### ISSUE TITLE
Can't import workflows or files

### ISSUE THREAD

**Issue by isaacliao** [StanfordBioinformatics/loom#184]
```
(loom) herring:~/venvs/loom/loom/loom/doc/examples/hello_world iliao$ loom import workflow hello_world.json 
Importing workflow from file:///Users/iliao/venvs/loom/loom/loom/doc/examples/hello_world/hello_world.json...
Traceback (most recent call last):
  File "/Users/iliao/venvs/loom/bin/loom", line 11, in <module>
load_entry_point('loomengine', 'console_scripts', 'loom')()
  File "/Users/iliao/venvs/loom/loom/loom/client/main.py", line 72, in main
Main().run()
  File "/Users/iliao/venvs/loom/loom/loom/client/main.py", line 68, in run
self.args.SubcommandClass(self.args).run()
  File "/Users/iliao/venvs/loom/loom/loom/client/importer.py", line 143, in run
self.args.SubSubcommandClass(self.args).run()
  File "/Users/iliao/venvs/loom/loom/loom/client/importer.py", line 73, in run
return self.import_workflow(self.args.workflow, self.args.note, self.filehandler, self.objecthandler, self.logger)
  File "/Users/iliao/venvs/loom/loom/loom/client/importer.py", line 84, in import_workflow
workflow_from_server = objecthandler.post_abstract_workflow(workflow)
  File "/Users/iliao/venvs/loom/loom/loom/common/objecthandler.py", line 181, in post_abstract_workflow
'abstract-workflows/')
  File "/Users/iliao/venvs/loom/loom/loom/common/objecthandler.py", line 89, in _post_object
return self._post(object_data, relative_url, raise_for_status=True).json()
  File "/Users/iliao/venvs/loom/loom/loom/common/objecthandler.py", line 32, in _post
raise_for_status=raise_for_status)
  File "/Users/iliao/venvs/loom/loom/loom/common/objecthandler.py", line 86, in _make_request_to_server
raise error
loom.common.exceptions
.
BadResponseError
:
500 Server Error: INTERNAL SERVER ERROR for url: https://104.155.171.105:443/api/abstract-workflows/
{"message": "Failed to find a subclass of model AbstractWorkflow that matches these fields: [u'inputs', u'fixed_inputs', u'name', u'workflow_import', u'outputs', u'steps', '_id'] and model_name: None"}
```
On the server, in loom_webserver.log:
```
ERROR [2016-08-29 23:41:48,000] Failed to create <class 'analysis.models.workflows.AbstractWorkflow'> with data "{"inputs": [{"type": "file", "channel": "hello", "hint": "Enter the 'hello' file"}, {"type": "file", "channel": "world", "hint": "Enter the 'world' file"}], "fixed_inputs": [{"type": "string", "value": "!!", "channel": "final_punc"}], "steps": [{"inputs": [{"type": "file", "channel": "hello"}], "name": "hello_step", "outputs": [{"type": "file", "channel": "hello_cap", "filename": "hello_cap.txt"}], "environment": {"docker_image": "ubuntu"}, "command": "cat {{ hello }} | tr '[a-z]' '[A-Z]' > {{ hello_cap }}", "resources": {"cores": "1", "memory": "1"}}, {"inputs": [{"type": "file", "channel": "world"}], "name": "world_step", "outputs": [{"type": "file", "channel": "world_cap", "filename": "world_cap.txt"}], "environment": {"docker_image": "ubuntu"}, "command": "cat {{ world }} | tr '[a-z]' '[A-Z]' > {{ world_cap }}", "resources": {"cores": "1", "memory": "1"}}, {"inputs": [{"type": "file", "channel": "hello_cap"}, {"type": "file", "channel": "world_cap"}, {"type": "string", "channel": "final_punc"}], "name": "hello_world_step", "outputs": [{"type": "file", "channel": "hello_world", "filename": "hello_world.txt"}], "environment": {"docker_image": "ubuntu"}, "command": "echo $(cat {{ hello_cap }} {{ world_cap }})'{{ final_punc}}' > {{ hello_world }}", "resources": {"cores": "1", "memory": "1"}}], "name": "hello_world", "workflow_import": {"note": null, "source_url": "file:///Users/iliao/venvs/loom/loom/loom/doc/examples/hello_world/hello_world.json"}, "outputs": [{"type": "file", "channel": "hello_world"}]}". Failed to find a subclass of model AbstractWorkflow that matches these fields: [u'inputs', u'fixed_inputs', u'name', u'workflow_import', u'outputs', u'steps', '_id'] and model_name: None
```
For files:
```
(loom) herring:~/venvs/loom/loom/loom/doc/examples/hello_world iliao$ loom import file hello.txt
Traceback (most recent call last):
  File "/Users/iliao/venvs/loom/bin/loom", line 11, in <module>
load_entry_point('loomengine', 'console_scripts', 'loom')()
  File "/Users/iliao/venvs/loom/loom/loom/client/main.py", line 72, in main
Main().run()
  File "/Users/iliao/venvs/loom/loom/loom/client/main.py", line 68, in run
self.args.SubcommandClass(self.args).run()
  File "/Users/iliao/venvs/loom/loom/loom/client/importer.py", line 143, in run
self.args.SubSubcommandClass(self.args).run()
  File "/Users/iliao/venvs/loom/loom/loom/client/importer.py", line 54, in run
self.args.note
  File "/Users/iliao/venvs/loom/loom/loom/common/filehandler.py", line 458, in import_from_patterns
self.import_from_pattern(pattern, note)
  File "/Users/iliao/venvs/loom/loom/loom/common/filehandler.py", line 464, in import_from_pattern
note
  File "/Users/iliao/venvs/loom/loom/loom/common/filehandler.py", line 469, in import_file
self._create_file_data_object_for_import(source_url, note),
  File "/Users/iliao/venvs/loom/loom/loom/common/filehandler.py", line 478, in _create_file_data_object_for_import
'source_url': Source(source_url, self.settings).get_url(),
  File "/Users/iliao/venvs/loom/loom/loom/common/objecthandler.py", line 118, in post_data_object
'data-objects/')
  File "/Users/iliao/venvs/loom/loom/loom/common/objecthandler.py", line 89, in _post_object
return self._post(object_data, relative_url, raise_for_status=True).json()
  File "/Users/iliao/venvs/loom/loom/loom/common/objecthandler.py", line 32, in _post
raise_for_status=raise_for_status)
  File "/Users/iliao/venvs/loom/loom/loom/common/objecthandler.py", line 86, in _make_request_to_server
raise error
loom.common.exceptions
.
BadResponseError
:
500 Server Error: INTERNAL SERVER ERROR for url: https://104.155.171.105:443/api/data-objects/
{"message": "Failed to find a subclass of model DataObject that matches these fields: [u'source_type', u'file_import'] and model_name: None"}
```

**Comment by nhammond** [comment]
I think you snagged an old version. Do you have DOCKER_TAG=development in your settings?

**Comment by isaacliao** [comment]
Oops, you're right. I had DOCKER_TAG=dockerized instead of development.
