### ISSUE TITLE
gce.py raises error when instances are being deleted

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#208]
Observed the same behavior twice. Reproduction steps: In the console, click "delete". While the instance is deleting, run "loom server set gcloud" and "loom server create".

ERROR! The file /Users/s0198839/PycharmProjects/loom/loomengine/utils/gce.py is marked as executable, but failed to execute correctly. If this is not supposed to be an executable script, correct this with `chmod -x /Users/s0198839/PycharmProjects/loom/loomengine/utils/gce.py`.
Inventory script (/Users/s0198839/PycharmProjects/loom/loomengine/utils/gce.py) had an execution error: Traceback (most recent call last):
  File "/Users/s0198839/PycharmProjects/loom/loomengine/utils/gce.py", line 376, in <module>
    GceInventory()
  File "/Users/s0198839/PycharmProjects/loom/loomengine/utils/gce.py", line 131, in **init**
    print(self.json_format_dict(self.group_instances(zones),
  File "/Users/s0198839/PycharmProjects/loom/loomengine/utils/gce.py", line 308, in group_instances
    for node in self.driver.list_nodes():
  File "/Users/s0198839/.virtualenvs/loom/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py", line 1629, in list_nodes
    v.get('instances', [])]
  File "/Users/s0198839/.virtualenvs/loom/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py", line 5362, in _to_node
    extra['boot_disk'] = self.ex_get_volume(bd['name'], bd['zone'])
  File "/Users/s0198839/.virtualenvs/loom/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py", line 4235, in ex_get_volume
    response = self.connection.request(request, method='GET').object
  File "/Users/s0198839/.virtualenvs/loom/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py", line 121, in request
    response = super(GCEConnection, self).request(_args, *_kwargs)
  File "/Users/s0198839/.virtualenvs/loom/lib/python2.7/site-packages/libcloud/common/google.py", line 777, in request
    _args, *_kwargs)
  File "/Users/s0198839/.virtualenvs/loom/lib/python2.7/site-packages/libcloud/common/base.py", line 854, in request
    response = responseCls(**kwargs)
  File "/Users/s0198839/.virtualenvs/loom/lib/python2.7/site-packages/libcloud/common/base.py", line 181, in __init__
    self.object = self.parse_body()
  File "/Users/s0198839/.virtualenvs/loom/lib/python2.7/site-packages/libcloud/common/google.py", line 269, in parse_body
    raise ResourceNotFoundError(message, self.status, code)
libcloud.common.google.ResourceNotFoundError: {'domain': 'global', 'message': "The resource 'projects/gbsc-gcp-project-scgs-dev/zones/us-central1-a/disks/nate-test-status1' was not found", 'reason': 'notFound'}

/Users/s0198839/PycharmProjects/loom/loomengine/utils/gce.py:19: Error parsing host definition ''''': No closing quotation

**Comment by nhammond** [comment]
This should be fixed by the retries in gce_wrapper.py.
