### ISSUE TITLE
.google_libcloud_auth credentials not deleted

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#230]
A file named ~/.google_libcloud_auth.[project_name] remains after server deletion. That causes an error the next time "loom server create" is executed with a different service account key.

The file should be cleaned up with 'loom server delete', and should also be stored under the .loom directory instead of as a hidden file at the user's home directory.

ERROR! Attempted to execute "/Users/s0198839/PycharmProjects/loom_dev/loom/loomengine/utils/gce.py" as inventory script: Inventory script (/Users/s0198839/PycharmProjects/loom_dev/loom/loomengine/utils/gce.py) had an execution error: Traceback (most recent call last):
  File "/Users/s0198839/PycharmProjects/loom_dev/loom/loomengine/utils/gce.py", line 376, in <module>
    GceInventory()
  File "/Users/s0198839/PycharmProjects/loom_dev/loom/loomengine/utils/gce.py", line 116, in __init__
    self.driver = self.get_gce_driver()
  File "/Users/s0198839/PycharmProjects/loom_dev/loom/loomengine/utils/gce.py", line 232, in get_gce_driver
    gce = get_driver(Provider.GCE)(*args, **kwargs)
  File "/Users/s0198839/PycharmProjects/loom_dev/env/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py", line 1354, in __init__
    self.zone_list = self.ex_list_zones()
  File "/Users/s0198839/PycharmProjects/loom_dev/env/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py", line 2259, in ex_list_zones
    response = self.connection.request(request, method='GET').object
  File "/Users/s0198839/PycharmProjects/loom_dev/env/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py", line 120, in request
    response = super(GCEConnection, self).request(*args, **kwargs)
  File "/Users/s0198839/PycharmProjects/loom_dev/env/lib/python2.7/site-packages/libcloud/common/google.py", line 806, in request
    *args, **kwargs)
  File "/Users/s0198839/PycharmProjects/loom_dev/env/lib/python2.7/site-packages/libcloud/common/base.py", line 862, in request
    response = responseCls(**kwargs)
  File "/Users/s0198839/PycharmProjects/loom_dev/env/lib/python2.7/site-packages/libcloud/common/base.py", line 181, in __init__
    self.object = self.parse_body()
  File "/Users/s0198839/PycharmProjects/loom_dev/env/lib/python2.7/site-packages/libcloud/common/google.py", line 294, in parse_body
    raise GoogleBaseError(message, self.status, code)
libcloud.common.google.GoogleBaseError: {u'locationType': u'header', u'domain': u'global', u'message': u'Invalid Credentials', u'reason': u'authError', u'location': u'Authorization'}

**Comment by isaacliao** [comment]
Added a function to do this in customserviceaccounts branch, but not merged to development yet: 05f713b5550f8e68c23b1b228663e134bc40e1c0

As for moving the credential file, will have to look into Apache libcloud to see if that's supported. We're not making the file; libcloud is. And we're not even using libcloud directly; it's an Ansible dependency.

**Comment by nhammond** [comment]
Deletion is working. I couldn't find an option to change the file path.
