### ISSUE TITLE
Setting Loom server IP in ALLOWED_HOSTS

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#231]
Django now requires that you explicitly set ALLOWED_HOSTS. Even when DEBUG=True, it allows only localhost.

We need a mechanism to set the ip address of a newly provisioned Loom server google cloud instance in ALLOWED_HOSTS.

**Comment by pbilling** [comment]
Using the latest version of the 'development' branch...

(loom-env) pbilling-display:loom pbilling$ loom server start
Starting Loom server...
Traceback (most recent call last):
  File "/Users/pbilling/Documents/GitHub/mvp_aaa_codelabs/loom_decrypt/loom-env/bin/loom", line 11, in <module>
    load_entry_point('loomengine', 'console_scripts', 'loom')()
  File "/Users/pbilling/Documents/GitHub/mvp_aaa_codelabs/loom_decrypt/loom/loomengine/client/main.py", line 72, in main
    Main().run()
  File "/Users/pbilling/Documents/GitHub/mvp_aaa_codelabs/loom_decrypt/loom/loomengine/client/main.py", line 68, in run
    self.args.SubcommandClass(self.args).run()
  File "/Users/pbilling/Documents/GitHub/mvp_aaa_codelabs/loom_decrypt/loom/loomengine/client/server.py", line 181, in start
    self._wait_for_server(target_running_state=True)
  File "/Users/pbilling/Documents/GitHub/mvp_aaa_codelabs/loom_decrypt/loom/loomengine/client/server.py", line 209, in _wait_for_server
    if is_server_running() == target_running_state:
  File "/Users/pbilling/Documents/GitHub/mvp_aaa_codelabs/loom_decrypt/loom/loomengine/client/common.py", line 155, in is_server_running
    raise Exception("Unexpected status code %s from server" % response.status_code)
Exception: Unexpected status code 400 from server

**Comment by isaacliao** [comment]
Error log from loom_django.log:
```
ERROR [2016-11-02 21:13:08,719] Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add u'127.0.0.1' to ALLOWED_HOSTS.
```
Tried setting `ALLOWED_HOSTS` in settings.py to `[u'127.0.0.1']`, but same error.

**Comment by nhammond** [comment]
Abandoning the workflow-dev branch. We will stabilize on a more recent version where these issues have already been fixed.
