### ISSUE TITLE
Failing test client.test.test_common.TestClientCommon.test_create_delete_service_account

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#232]
(eng) LAP14728m:loom-dev s0198839$ cd loom/loomengine/client/test
(eng) LAP14728m:test s0198839$ python -m unittest discover
Your active configuration is: [default]

Your active configuration is: [default]

Your active configuration is: [default]

EYour active configuration is: [default]

......
======================================================================
ERROR: test_create_delete_service_account (test_common.TestClientCommon)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/s0198839/PycharmProjects/loom-dev/loom/loomengine/client/test/test_common.py", line 23, in test_create_delete_service_account
    delete_service_account(account_email)
  File "/Users/s0198839/PycharmProjects/loom-dev/loom/loomengine/client/common.py", line 275, in delete_service_account
    response = request.execute()
  File "/Users/s0198839/PycharmProjects/loom-dev/eng/lib/python2.7/site-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/s0198839/PycharmProjects/loom-dev/eng/lib/python2.7/site-packages/googleapiclient/http.py", line 838, in execute
    raise HttpError(resp, content, uri=self.uri)
HttpError: <HttpError 404 when requesting https://iam.googleapis.com/v1/projects/gbsc-gcp-project-scgs-dev/serviceAccounts/None?alt=json returned "Requested entity was not found.">

----------------------------------------------------------------------
Ran 7 tests in 3.562s

**Comment by nhammond** [comment]
Test was removed.
