### ISSUE TITLE
Failure provisioning worker and creating task run

### ISSUE THREAD

**Issue by isaacliao** [StanfordBioinformatics/loom#238]
From loom_master.log:
```
ERROR [2016-11-09 20:36:24,388] Failed to provision host.
Traceback (most recent call last):
  File "/opt/loom/loomengine/master/api/task_manager/cloud.py", line 121, in _run
    cls._run_playbook(GCLOUD_CREATE_WORKER_PLAYBOOK, playbook_vars, logfile=ansible_logfile)
  File "/opt/loom/loomengine/master/api/task_manager/cloud.py", line 169, in _run_playbook
    raise Exception('Nonzero returncode %s for command: %s' % (returncode, ' '.join(cmd)))
Exception: Nonzero returncode 2 for command: ansible-playbook -vvv --key-file /root/.ssh/google_compute_engine -i /opt/loom/loomengine/utils/gce.py /opt/loom/loomengine/playbooks/gcloud_create_worker.yml --extra-vars {"docker_full_name": "loomengine/loom:customserviceaccounts", "gce_ssh_key_file": "/root/.ssh/google_compute_engine", "boot_disk_type": "pd-ssd", "task_run_attempt_id": "9a345d1c31bb40379528d2bd29efdd70", "worker_log_file": "/mnt/loomdata/runtime_volumes/9a345d1c31bb40379528d2bd29efdd70/logs/worker.log", "remote_user": "loom", "log_level": "INFO", "network": "development", "zone": "us-central1-a", "gce_credential": "/root/.loom/gce_key.json", "scratch_disk_mount_point": "/mnt/loomdata", "scratch_disk_device_path": "/dev/disk/by-id/google-isaac-roles-hellostep-9a345d1c31bb40379528d2bd29efdd70-disk", "tags": "computes-uscentral", "boot_disk_size_gb": "163", "master_url": "https://isaac-roles:443", "scratch_disk_size_gb": "163", "docker_tag": "customserviceaccounts", "scratch_disk_name": "isaac-roles-hellostep-9a345d1c31bb40379528d2bd29efdd70-disk", "use_internal_ip": "True", "gce_email": "isaac-roles@gbsc-gcp-project-scgs-dev.iam.gserviceaccount.com", "scratch_disk_type": "pd-ssd", "instance_image": "centos-7", "instance_name": "isaac-roles-hellostep-9a345d1c31bb40379528d2bd29efdd70", "instance_type": "n1-standard-1", "subnetwork": "computes-uscentral", "task_run_docker_image": "ubuntu"}
ERROR [2016-11-09 20:36:24,389] Failed to create task run attempt 9a345d1c31bb40379528d2bd29efdd70: post_task_run_attempt_error() takes exactly 3 arguments (2 given)
Traceback (most recent call last):
  File "/opt/loom/loomengine/master/api/task_manager/cloud.py", line 63, in _try_run
    cls._run(task_run_attempt_id, requested_resources, environment, worker_name, worker_log_file)
  File "/opt/loom/loomengine/master/api/task_manager/cloud.py", line 126, in _run
    'detail': str(e)
TypeError: post_task_run_attempt_error() takes exactly 3 arguments (2 given)
```
Using this settings file:
```
[gcloud]
DOCKER_TAG = customserviceaccounts
WORKER_USES_SERVER_INTERNAL_IP = True
CLIENT_USES_SERVER_INTERNAL_IP = True

SERVER_NETWORK = development
SERVER_CUSTOM_SUBNET = computes-uscentral
SERVER_LOCATION = us-central1-a
SERVER_TAGS = computes-uscentral,https-server

WORKER_NETWORK = development
WORKER_CUSTOM_SUBNET = computes-uscentral
WORKER_LOCATION = us-central1-a
WORKER_TAGS = computes-uscentral

SERVICE_ACCOUNT_ROLES = ["roles/compute.instanceAdmin", "roles/compute.storageAdmin", "roles/logging.logWriter", "roles/storage.objectCreator", "roles/storage.objectViewer", "roles/logging.viewer", "roles/iam.serviceAccountActor"]
```

**Comment by isaacliao** [comment]
Also seen when using a custom service account and not specifying custom roles:
```
ERROR [2016-11-10 23:58:22,967] Failed to provision host.
Traceback (most recent call last):
  File "/opt/loom/loomengine/master/api/task_manager/cloud.py", line 121, in _run
    cls._run_playbook(GCLOUD_CREATE_WORKER_PLAYBOOK, playbook_vars, logfile=ansible_logfile)
  File "/opt/loom/loomengine/master/api/task_manager/cloud.py", line 169, in _run_playbook
    raise Exception('Nonzero returncode %s for command: %s' % (returncode, ' '.join(cmd)))
Exception: Nonzero returncode 2 for command: ansible-playbook -vvv --key-file /root/.ssh/google_compute_engine -i /opt/loom/loomengine/utils/gce.py /opt/loom/loomengine/playbooks/gcloud_create_worker.yml --extra-vars {"docker_full_name": "loomengine/loom:customserviceaccounts", "gce_ssh_key_file": "/root/.ssh/google_compute_engine", "boot_disk_type": "pd-ssd", "task_run_attempt_id": "14f1adfdba8f45ac9a454e37283fcc03", "worker_log_file": "/mnt/loomdata/runtime_volumes/14f1adfdba8f45ac9a454e37283fcc03/logs/worker.log", "remote_user": "loom", "log_level": "INFO", "network": "development", "zone": "us-central1-a", "gce_credential": "/root/.loom/gce_key.json", "scratch_disk_mount_point": "/mnt/loomdata", "scratch_disk_device_path": "/dev/disk/by-id/google-isaac-custom4-hellostep-14f1adfdba8f45ac9a454e37283fcc03-disk", "tags": "computes-uscentral", "boot_disk_size_gb": "163", "master_url": "https://isaac-custom4:443", "scratch_disk_size_gb": "163", "docker_tag": "customserviceaccounts", "scratch_disk_name": "isaac-custom4-hellostep-14f1adfdba8f45ac9a454e37283fcc03-disk", "use_internal_ip": "True", "gce_email": "isaac-custom2@gbsc-gcp-project-scgs-dev.iam.gserviceaccount.com", "scratch_disk_type": "pd-ssd", "instance_image": "centos-7", "instance_name": "isaac-custom4-hellostep-14f1adfdba8f45ac9a454e37283fcc03", "instance_type": "n1-standard-1", "subnetwork": "computes-uscentral", "task_run_docker_image": "ubuntu"}
ERROR [2016-11-10 23:58:22,967] Failed to create task run attempt 14f1adfdba8f45ac9a454e37283fcc03: post_task_run_attempt_error() takes exactly 3 arguments (2 given)
Traceback (most recent call last):
  File "/opt/loom/loomengine/master/api/task_manager/cloud.py", line 63, in _try_run
    cls._run(task_run_attempt_id, requested_resources, environment, worker_name, worker_log_file)
  File "/opt/loom/loomengine/master/api/task_manager/cloud.py", line 126, in _run
    'detail': str(e)
TypeError: post_task_run_attempt_error() takes exactly 3 arguments (2 given)
```
Settings file:
```
[gcloud]
DOCKER_TAG = customserviceaccounts
WORKER_USES_SERVER_INTERNAL_IP = True
CLIENT_USES_SERVER_INTERNAL_IP = True
 
SERVER_NETWORK = development
SERVER_CUSTOM_SUBNET = computes-uscentral
SERVER_LOCATION = us-central1-a
SERVER_TAGS = computes-uscentral,https-server

WORKER_NETWORK = development
WORKER_CUSTOM_SUBNET = computes-uscentral
WORKER_LOCATION = us-central1-a
WORKER_TAGS = computes-uscentral

CUSTOM_SERVICE_ACCOUNT_EMAIL = isaac-custom2@gbsc-gcp-project-scgs-dev.iam.gserviceaccount.com
```

**Comment by isaacliao** [comment]
Obsolete, the task manager doesn't exist any more.
