### ISSUE TITLE
Imported files registered in database even if import fails

### ISSUE THREAD

**Issue by isaacliao** [StanfordBioinformatics/loom#244]
While determining needed roles for service account (which is why the import failed the first time):
```
(loom-env) iliao@isaac-jenkins-loom-test:~/loom/doc/examples/hello_world$ loom import file hello.txt
Importing file from file:///home/iliao/loom/doc/examples/hello_world/hello.txt...
   calculating md5 hash...
Traceback (most recent call last):
  File "/home/iliao/loom-env/bin/loom", line 11, in <module>
    load_entry_point('loomengine', 'console_scripts', 'loom')()
  File "/home/iliao/loom/loomengine/client/main.py", line 72, in main
    Main().run()
  File "/home/iliao/loom/loomengine/client/main.py", line 68, in run
    self.args.SubcommandClass(self.args).run()
  File "/home/iliao/loom/loomengine/client/importer.py", line 136, in run
    self.args.SubSubcommandClass(self.args).run()
  File "/home/iliao/loom/loomengine/client/importer.py", line 46, in run
    self.args.note
  File "/home/iliao/loom/loomengine/utils/filemanager.py", line 453, in import_from_patterns
    files.extend(self.import_from_pattern(pattern, note))
  File "/home/iliao/loom/loomengine/utils/filemanager.py", line 461, in import_from_pattern
    note
  File "/home/iliao/loom/loomengine/utils/filemanager.py", line 468, in import_file
    source_url
  File "/home/iliao/loom/loomengine/utils/filemanager.py", line 535, in _execute_file_import
    self.settings)
  File "/home/iliao/loom/loomengine/utils/filemanager.py", line 252, in Destination
    return GoogleStorageDestination(url, settings)
  File "/home/iliao/loom/loomengine/utils/filemanager.py", line 325, in __init__
    self.bucket = self.client.get_bucket(self.bucket_id)
  File "/home/iliao/loom-env/local/lib/python2.7/site-packages/gcloud/storage/client.py", line 167, in get_bucket
    bucket.reload(client=self)
  File "/home/iliao/loom-env/local/lib/python2.7/site-packages/gcloud/storage/_helpers.py", line 77, in reload
    _target_object=self)
  File "/home/iliao/loom-env/local/lib/python2.7/site-packages/gcloud/connection.py", line 347, in api_request
    error_info=method + ' ' + url)
gcloud.exceptions.Forbidden: 403 Forbidden (GET https://www.googleapis.com/storage/v1/b/gbsc-gcp-project-scgs-dev-loom?projection=noAcl)
(loom-env) iliao@isaac-jenkins-loom-test:~/loom/doc/examples/hello_world$ loom import file hello.txt
Importing file from file:///home/iliao/loom/doc/examples/hello_world/hello.txt...
   calculating md5 hash...
   copying to destination gs://gbsc-gcp-project-scgs-dev-loom/root/loomdata/imported/20161114205254-c990e4c991ca4aa9ac1295d49e9f5106-hello.txt...
   imported file hello.txt@c990e4c991ca4aa9ac1295d49e9f5106
(loom-env) iliao@isaac-jenkins-loom-test:~/loom/doc/examples/hello_world$ loom import file world.txt
Importing file from file:///home/iliao/loom/doc/examples/hello_world/world.txt...
   calculating md5 hash...
Traceback (most recent call last):
  File "/home/iliao/loom-env/bin/loom", line 11, in <module>
    load_entry_point('loomengine', 'console_scripts', 'loom')()
  File "/home/iliao/loom/loomengine/client/main.py", line 72, in main
    Main().run()
  File "/home/iliao/loom/loomengine/client/main.py", line 68, in run
    self.args.SubcommandClass(self.args).run()
  File "/home/iliao/loom/loomengine/client/importer.py", line 136, in run
    self.args.SubSubcommandClass(self.args).run()
  File "/home/iliao/loom/loomengine/client/importer.py", line 46, in run
    self.args.note
  File "/home/iliao/loom/loomengine/utils/filemanager.py", line 453, in import_from_patterns
    files.extend(self.import_from_pattern(pattern, note))
  File "/home/iliao/loom/loomengine/utils/filemanager.py", line 461, in import_from_pattern
    note
  File "/home/iliao/loom/loomengine/utils/filemanager.py", line 468, in import_file
    source_url
  File "/home/iliao/loom/loomengine/utils/filemanager.py", line 535, in _execute_file_import
    self.settings)
  File "/home/iliao/loom/loomengine/utils/filemanager.py", line 252, in Destination
    return GoogleStorageDestination(url, settings)
  File "/home/iliao/loom/loomengine/utils/filemanager.py", line 325, in __init__
    self.bucket = self.client.get_bucket(self.bucket_id)
  File "/home/iliao/loom-env/local/lib/python2.7/site-packages/gcloud/storage/client.py", line 167, in get_bucket
    bucket.reload(client=self)
  File "/home/iliao/loom-env/local/lib/python2.7/site-packages/gcloud/storage/_helpers.py", line 77, in reload
    _target_object=self)
  File "/home/iliao/loom-env/local/lib/python2.7/site-packages/gcloud/connection.py", line 347, in api_request
    error_info=method + ' ' + url)
gcloud.exceptions.Forbidden: 403 Forbidden (GET https://www.googleapis.com/storage/v1/b/gbsc-gcp-project-scgs-dev-loom?projection=noAcl)
(loom-env) iliao@isaac-jenkins-loom-test:~/loom/doc/examples/hello_world$ loom import file world.txt
Importing file from file:///home/iliao/loom/doc/examples/hello_world/world.txt...
   calculating md5 hash...
   copying to destination gs://gbsc-gcp-project-scgs-dev-loom/root/loomdata/imported/20161114205410-10b8dd78b7da4e9fad44692e4a3e5b02-world.txt...
   imported file world.txt@10b8dd78b7da4e9fad44692e4a3e5b02
(loom-env) iliao@isaac-jenkins-loom-test:~/loom/doc/examples/hello_world$ loom import workflow hello_world.json 
Importing workflow from file:///home/iliao/loom/doc/examples/hello_world/hello_world.json...
   imported workflow hello_world@6d706fd0f21a402a8709a311fedfe4b9
(loom-env) iliao@isaac-jenkins-loom-test:~/loom/doc/examples/hello_world$ loom run hello_world hello=hello.txt world=world.txt
Traceback (most recent call last):
  File "/home/iliao/loom-env/bin/loom", line 11, in <module>
    load_entry_point('loomengine', 'console_scripts', 'loom')()
  File "/home/iliao/loom/loomengine/client/main.py", line 72, in main
    Main().run()
  File "/home/iliao/loom/loomengine/client/main.py", line 68, in run
    self.args.SubcommandClass(self.args).run()
  File "/home/iliao/loom/loomengine/client/run.py", line 53, in run
    'inputs': self._get_inputs()
  File "/home/iliao/loom/loomengine/utils/connection.py", line 221, in post_run_request
    'run-requests/')
  File "/home/iliao/loom/loomengine/utils/connection.py", line 104, in _post_object
    return self._post(object_data, relative_url).json()
  File "/home/iliao/loom/loomengine/utils/connection.py", line 41, in _post
    lambda: requests.post(
  File "/home/iliao/loom/loomengine/utils/connection.py", line 101, in _make_request_to_server
    raise error
loomengine.utils.exceptions.BadResponseError: 500 Server Error: Internal Server Error for url: https://10.2.80.3:443/api/run-requests/
Exception at /api/run-requests/
Expected one file but found 2 for value hello.txt

Request Method: POST
Request URL: http://10.2.80.3/api/run-requests/
Django Version: 1.10.3
Python Executable: /opt/loom/bin/python
Python Version: 2.7.9
Python Path: ['/', '/opt/loom/bin', '/opt/loom/loomengine/master', '/', '/opt/loom/lib/python2.7', '/opt/loom/lib/python2.7/plat-x86_64-linux-gnu', '/opt/loom/lib/python2.7/lib-tk', '/opt/loom/lib/python2.7/lib-old', '/opt/loom/lib/python2.7/lib-dynload', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/opt/loom/local/lib/python2.7/site-packages', '/opt/loom', '/opt/loom/lib/python2.7/site-packages']
Server time: Mon, 14 Nov 2016 20:55:04 +0000
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django_extensions',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'corsheaders',
 'polymorphic',
 'rest_framework',
 'api')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware')


Traceback:  

File "/opt/loom/local/lib/python2.7/site-packages/django/core/handlers/exception.py" in inner
  39.             response = get_response(request)

File "/opt/loom/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _legacy_get_response
  249.             response = self._get_response(request)

File "/opt/loom/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/opt/loom/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/opt/loom/local/lib/python2.7/site-packages/django/views/decorators/csrf.py" in wrapped_view
  58.         return view_func(*args, **kwargs)

File "/opt/loom/local/lib/python2.7/site-packages/rest_framework/viewsets.py" in view
  83.             return self.dispatch(request, *args, **kwargs)

File "/opt/loom/local/lib/python2.7/site-packages/rest_framework/views.py" in dispatch
  477.             response = self.handle_exception(exc)

File "/opt/loom/local/lib/python2.7/site-packages/rest_framework/views.py" in handle_exception
  437.             self.raise_uncaught_exception(exc)

File "/opt/loom/local/lib/python2.7/site-packages/rest_framework/views.py" in raise_uncaught_exception
  448.         raise exc

Exception Type: Exception at /api/run-requests/
Exception Value: Expected one file but found 2 for value hello.txt
Request information:
USER: AnonymousUser

GET: No GET data

POST: No POST data

FILES: No FILES data

COOKIES: No cookie data

META:
CONTENT_LENGTH = '125'
CONTENT_TYPE = 'application/json'
HTTP_ACCEPT = '*/*'
HTTP_ACCEPT_ENCODING = 'gzip, deflate'
HTTP_HOST = '10.2.80.3'
HTTP_USER_AGENT = 'python-requests/2.11.1'
HTTP_X_FORWARDED_FOR = '10.2.16.7'
HTTP_X_REAL_IP = '10.2.16.7'
PATH_INFO = u'/api/run-requests/'
QUERY_STRING = ''
RAW_URI = '/api/run-requests/'
REMOTE_ADDR = '172.17.0.1'
REMOTE_PORT = '57596'
REQUEST_METHOD = 'POST'
SCRIPT_NAME = u''
SERVER_NAME = '0.0.0.0'
SERVER_PORT = '8000'
SERVER_PROTOCOL = 'HTTP/1.1'
SERVER_SOFTWARE = 'gunicorn/19.6.0'
gunicorn.socket = <socket._socketobject object at 0x7fa92b9d33d0>
wsgi.errors = <gunicorn.http.wsgi.WSGIErrorsWrapper object at 0x7fa92b9fd0d0>
wsgi.file_wrapper = ''
wsgi.input = <gunicorn.http.body.Body object at 0x7fa92ba0f8d0>
wsgi.multiprocess = False
wsgi.multithread = False
wsgi.run_once = False
wsgi.url_scheme = 'http'
wsgi.version = 

Settings:
Using settings module loomengine.master.settings
ABSOLUTE_URL_OVERRIDES = {}
ADMINS = []
ALLOWED_HOSTS = ['*']
APPEND_SLASH = False
AUTHENTICATION_BACKENDS = [u'django.contrib.auth.backends.ModelBackend']
AUTH_PASSWORD_VALIDATORS = u'********************'
AUTH_USER_MODEL = u'auth.User'
BASE_DIR = '/opt/loom/loomengine/master'
BUCKET_ID = 'gbsc-gcp-project-scgs-dev-loom'
CACHES = {u'default': {u'BACKEND': u'django.core.cache.backends.locmem.LocMemCache'}}
CACHE_MIDDLEWARE_ALIAS = u'default'
CACHE_MIDDLEWARE_KEY_PREFIX = u'********************'
CACHE_MIDDLEWARE_SECONDS = 600
CORS_ORIGIN_ALLOW_ALL = False
CORS_ORIGIN_WHITELIST = ['']
CSRF_COOKIE_AGE = 31449600
CSRF_COOKIE_DOMAIN = None
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_NAME = u'csrftoken'
CSRF_COOKIE_PATH = u'/'
CSRF_COOKIE_SECURE = False
CSRF_FAILURE_VIEW = u'django.views.csrf.csrf_failure'
CSRF_HEADER_NAME = u'HTTP_X_CSRFTOKEN'
CSRF_TRUSTED_ORIGINS = []
DATABASES = {'default': {'ENGINE': 'django.db.backends.sqlite3', 'AUTOCOMMIT': True, 'ATOMIC_REQUESTS': False, 'NAME': '/root/.loom/loom-database.sqlite3', 'CONN_MAX_AGE': 0, 'TIME_ZONE': None, 'OPTIONS': {}, 'HOST': '', 'USER': '', 'TEST': {'COLLATION': None, 'CHARSET': None, 'NAME': None, 'MIRROR': None}, 'PASSWORD': u'********************', 'PORT': ''}}
DATABASE_ROUTERS = []
DATA_UPLOAD_MAX_MEMORY_SIZE = 2621440
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000
DATETIME_FORMAT = u'N j, Y, P'
DATETIME_INPUT_FORMATS = [u'%Y-%m-%d %H:%M:%S', u'%Y-%m-%d %H:%M:%S.%f', u'%Y-%m-%d %H:%M', u'%Y-%m-%d', u'%m/%d/%Y %H:%M:%S', u'%m/%d/%Y %H:%M:%S.%f', u'%m/%d/%Y %H:%M', u'%m/%d/%Y', u'%m/%d/%y %H:%M:%S', u'%m/%d/%y %H:%M:%S.%f', u'%m/%d/%y %H:%M', u'%m/%d/%y']
DATE_FORMAT = u'N j, Y'
DATE_INPUT_FORMATS = [u'%Y-%m-%d', u'%m/%d/%Y', u'%m/%d/%y', u'%b %d %Y', u'%b %d, %Y', u'%d %b %Y', u'%d %b, %Y', u'%B %d %Y', u'%B %d, %Y', u'%d %B %Y', u'%d %B, %Y']
DEBUG = True
DEBUG_PROPAGATE_EXCEPTIONS = False
DECIMAL_SEPARATOR = u'.'
DEFAULT_CHARSET = u'utf-8'
DEFAULT_CONTENT_TYPE = u'text/html'
DEFAULT_EXCEPTION_REPORTER_FILTER = u'django.views.debug.SafeExceptionReporterFilter'
DEFAULT_FILE_STORAGE = u'django.core.files.storage.FileSystemStorage'
DEFAULT_FROM_EMAIL = u'webmaster@localhost'
DEFAULT_INDEX_TABLESPACE = u''
DEFAULT_TABLESPACE = u''
DISABLE_AUTO_PUSH = False
DISALLOWED_USER_AGENTS = []
DOCKER_FULL_NAME = 'loomengine/loom:customserviceaccounts'
DOCKER_TAG = 'customserviceaccounts'
EMAIL_BACKEND = u'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = u'localhost'
EMAIL_HOST_PASSWORD = u'********************'
EMAIL_HOST_USER = u''
EMAIL_PORT = 25
EMAIL_SSL_CERTFILE = None
EMAIL_SSL_KEYFILE = u'********************'
EMAIL_SUBJECT_PREFIX = u'[Django] '
EMAIL_TIMEOUT = None
EMAIL_USE_SSL = False
EMAIL_USE_TLS = False
FILE_CHARSET = u'utf-8'
FILE_ROOT = '/root/loomdata'
FILE_ROOT_FOR_WORKER = '/mnt/loomdata'
FILE_SERVER_TYPE = 'GOOGLE_CLOUD'
FILE_UPLOAD_DIRECTORY_PERMISSIONS = None
FILE_UPLOAD_HANDLERS = [u'django.core.files.uploadhandler.MemoryFileUploadHandler', u'django.core.files.uploadhandler.TemporaryFileUploadHandler']
FILE_UPLOAD_MAX_MEMORY_SIZE = 2621440
FILE_UPLOAD_PERMISSIONS = None
FILE_UPLOAD_TEMP_DIR = None
FIRST_DAY_OF_WEEK = 0
FIXTURE_DIRS = []
FORCE_RERUN = True
FORCE_SCRIPT_NAME = None
FORMAT_MODULE_PATH = None
GCE_EMAIL = 'jenkins-loom-test@gbsc-gcp-project-scgs-dev.iam.gserviceaccount.com'
GCE_INI_PATH = '/root/.loom/gce.ini'
GCE_PEM_FILE_PATH = '/root/.loom/gce_key.json'
GCE_SSH_KEY_FILE = u'********************'
HARD_STOP_ON_CANCEL = True
HARD_STOP_ON_FAIL = True
HASH_FUNCTION = 'md5'
IGNORABLE_404_URLS = []
INSTALLED_APPS = 
INTERNAL_IPS = []
KEEP_DUPLICATE_FILES = True
LANGUAGES = [(u'af', u'Afrikaans'), (u'ar', u'Arabic'), (u'ast', u'Asturian'), (u'az', u'Azerbaijani'), (u'bg', u'Bulgarian'), (u'be', u'Belarusian'), (u'bn', u'Bengali'), (u'br', u'Breton'), (u'bs', u'Bosnian'), (u'ca', u'Catalan'), (u'cs', u'Czech'), (u'cy', u'Welsh'), (u'da', u'Danish'), (u'de', u'German'), (u'dsb', u'Lower Sorbian'), (u'el', u'Greek'), (u'en', u'English'), (u'en-au', u'Australian English'), (u'en-gb', u'British English'), (u'eo', u'Esperanto'), (u'es', u'Spanish'), (u'es-ar', u'Argentinian Spanish'), (u'es-co', u'Colombian Spanish'), (u'es-mx', u'Mexican Spanish'), (u'es-ni', u'Nicaraguan Spanish'), (u'es-ve', u'Venezuelan Spanish'), (u'et', u'Estonian'), (u'eu', u'Basque'), (u'fa', u'Persian'), (u'fi', u'Finnish'), (u'fr', u'French'), (u'fy', u'Frisian'), (u'ga', u'Irish'), (u'gd', u'Scottish Gaelic'), (u'gl', u'Galician'), (u'he', u'Hebrew'), (u'hi', u'Hindi'), (u'hr', u'Croatian'), (u'hsb', u'Upper Sorbian'), (u'hu', u'Hungarian'), (u'ia', u'Interlingua'), (u'id', u'Indonesian'), (u'io', u'Ido'), (u'is', u'Icelandic'), (u'it', u'Italian'), (u'ja', u'Japanese'), (u'ka', u'Georgian'), (u'kk', u'Kazakh'), (u'km', u'Khmer'), (u'kn', u'Kannada'), (u'ko', u'Korean'), (u'lb', u'Luxembourgish'), (u'lt', u'Lithuanian'), (u'lv', u'Latvian'), (u'mk', u'Macedonian'), (u'ml', u'Malayalam'), (u'mn', u'Mongolian'), (u'mr', u'Marathi'), (u'my', u'Burmese'), (u'nb', u'Norwegian Bokm\xe5l'), (u'ne', u'Nepali'), (u'nl', u'Dutch'), (u'nn', u'Norwegian Nynorsk'), (u'os', u'Ossetic'), (u'pa', u'Punjabi'), (u'pl', u'Polish'), (u'pt', u'Portuguese'), (u'pt-br', u'Brazilian Portuguese'), (u'ro', u'Romanian'), (u'ru', u'Russian'), (u'sk', u'Slovak'), (u'sl', u'Slovenian'), (u'sq', u'Albanian'), (u'sr', u'Serbian'), (u'sr-latn', u'Serbian Latin'), (u'sv', u'Swedish'), (u'sw', u'Swahili'), (u'ta', u'Tamil'), (u'te', u'Telugu'), (u'th', u'Thai'), (u'tr', u'Turkish'), (u'tt', u'Tatar'), (u'udm', u'Udmurt'), (u'uk', u'Ukrainian'), (u'ur', u'Urdu'), (u'vi', u'Vietnamese'), (u'zh-hans', u'Simplified Chinese'), (u'zh-hant', u'Traditional Chinese')]
LANGUAGES_BIDI = [u'he', u'ar', u'fa', u'ur']
LANGUAGE_CODE = 'en-us'
LANGUAGE_COOKIE_AGE = None
LANGUAGE_COOKIE_DOMAIN = None
LANGUAGE_COOKIE_NAME = u'django_language'
LANGUAGE_COOKIE_PATH = u'/'
LOCALE_PATHS = []
LOGGING = {'loggers': {'loomengine': {'handlers': ['loomengine_handler'], 'level': 'INFO'}, 'api': u'********************', 'django': {'handlers': ['django_handler'], 'level': 'INFO'}}, 'version': 1, 'formatters': {'default': {'format': '%(levelname)s [%(asctime)s] %(message)s'}}, 'disable_existing_loggers': False, 'handlers': {'loomengine_handler': {'formatter': 'default', 'class': 'logging.FileHandler', 'filename': '/root/.loom/log/loom_master.log'}, 'django_handler': {'formatter': 'default', 'class': 'logging.FileHandler', 'filename': '/root/.loom/log/loom_django.log'}}}
LOGGING_CONFIG = u'logging.config.dictConfig'
LOGIN_REDIRECT_URL = u'/accounts/profile/'
LOGIN_URL = u'/accounts/login/'
LOGOUT_REDIRECT_URL = None
LOGS_DIR = '/root/.loom/log'
LOG_LEVEL = 'INFO'
LOOM_MYSQL_DB_NAME = None
LOOM_MYSQL_HOST = None
LOOM_MYSQL_PASSWORD = u'********************'
LOOM_MYSQL_PORT = None
LOOM_MYSQL_SSL_CA_CERT_PATH = None
LOOM_MYSQL_SSL_CLIENT_CERT_PATH = None
LOOM_MYSQL_SSL_CLIENT_KEY_PATH = u'********************'
LOOM_MYSQL_USER = None
LOOM_SETTINGS_PATH = '/root/.loom/'
MANAGERS = []
MASTER_URL_FOR_SERVER = 'http://localhost:8000'
MASTER_URL_FOR_WORKER = 'https://isaac-custom:443'
MEDIA_ROOT = u''
MEDIA_URL = u''
MESSAGE_STORAGE = u'django.contrib.messages.storage.fallback.FallbackStorage'
MIDDLEWARE = None
MIDDLEWARE_CLASSES = 
MIGRATION_MODULES = {}
MONTH_DAY_FORMAT = u'F j'
NUMBER_GROUPING = 0
PASSWORD_HASHERS = u'********************'
PASSWORD_RESET_TIMEOUT_DAYS = u'********************'
PREPEND_WWW = False
PROJECT_ID = 'gbsc-gcp-project-scgs-dev'
REST_FRAMEWORK = {'DEFAULT_RENDERER_CLASSES': ('rest_framework.renderers.JSONRenderer',), 'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.AllowAny',)}
ROOT_URLCONF = 'loomengine.master.urls'
SECRET_KEY = u'********************'
SECURE_BROWSER_XSS_FILTER = False
SECURE_CONTENT_TYPE_NOSNIFF = False
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_SECONDS = 0
SECURE_PROXY_SSL_HEADER = None
SECURE_REDIRECT_EXEMPT = []
SECURE_SSL_HOST = None
SECURE_SSL_REDIRECT = False
SERVER_EMAIL = u'root@localhost'
SERVER_SKIP_INSTALLS = 'False'
SESSION_CACHE_ALIAS = u'default'
SESSION_COOKIE_AGE = 1209600
SESSION_COOKIE_DOMAIN = None
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_NAME = u'sessionid'
SESSION_COOKIE_PATH = u'/'
SESSION_COOKIE_SECURE = False
SESSION_ENGINE = u'django.contrib.sessions.backends.db'
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_FILE_PATH = None
SESSION_SAVE_EVERY_REQUEST = False
SESSION_SERIALIZER = u'django.contrib.sessions.serializers.JSONSerializer'
SETTINGS_MODULE = 'loomengine.master.settings'
SHORT_DATETIME_FORMAT = u'm/d/Y P'
SHORT_DATE_FORMAT = u'm/d/Y'
SIGNING_BACKEND = u'django.core.signing.TimestampSigner'
SILENCED_SYSTEM_CHECKS = []
STATICFILES_DIRS = ['/opt/loom/loomengine/portal']
STATICFILES_FINDERS = [u'django.contrib.staticfiles.finders.FileSystemFinder', u'django.contrib.staticfiles.finders.AppDirectoriesFinder']
STATICFILES_STORAGE = u'django.contrib.staticfiles.storage.StaticFilesStorage'
STATIC_ROOT = None
STATIC_URL = '/home/'
TEMPLATES = []
TEMPLATE_DEBUG = True
TEST_NON_SERIALIZED_APPS = []
TEST_RUNNER = u'django.test.runner.DiscoverRunner'
THOUSAND_SEPARATOR = u','
TIME_FORMAT = u'P'
TIME_INPUT_FORMATS = [u'%H:%M:%S', u'%H:%M:%S.%f', u'%H:%M']
TIME_ZONE = 'UTC'
USE_ETAGS = False
USE_I18N = True
USE_L10N = False
USE_THOUSAND_SEPARATOR = False
USE_TZ = True
USE_X_FORWARDED_HOST = False
USE_X_FORWARDED_PORT = False
WEBPORTAL_ROOT = '/opt/loom/loomengine/portal'
WORKER_BOOT_DISK_SIZE = '163'
WORKER_BOOT_DISK_TYPE = 'pd-ssd'
WORKER_CUSTOM_SUBNET = 'computes-uscentral'
WORKER_LOCATION = 'us-central1-a'
WORKER_NETWORK = 'development'
WORKER_SCRATCH_DISK_MOUNT_POINT = '/mnt/loomdata'
WORKER_SCRATCH_DISK_SIZE = '163'
WORKER_SCRATCH_DISK_TYPE = 'pd-ssd'
WORKER_SKIP_INSTALLS = 'False'
WORKER_TAGS = 'computes-uscentral'
WORKER_TYPE = 'GOOGLE_CLOUD'
WORKER_USES_SERVER_INTERNAL_IP = 'True'
WORKER_VM_IMAGE = 'centos-7'
WSGI_APPLICATION = 'loomengine.master.wsgi.application'
X_FRAME_OPTIONS = u'SAMEORIGIN'
YEAR_MONTH_FORMAT = u'F Y'


You're seeing this error because you have DEBUG = True in your
Django settings file. Change that to False, and Django will
display a standard page generated by the handler for this status code.


(loom-env) iliao@isaac-jenkins-loom-test:~/loom/doc/examples/hello_world$ loom show files
File: hello.txt@6899e1638530418e864f26aaffae549d
File: hello.txt@c990e4c991ca4aa9ac1295d49e9f5106
File: world.txt@059278a9767f481cb096dbf2e2466830
File: world.txt@10b8dd78b7da4e9fad44692e4a3e5b02

(loom-env) iliao@isaac-jenkins-loom-test:~/loom/doc/examples/hello_world$ loom run hello_world hello=hello.txt@c99 world=world.txt@10b8dd
Created run request hello_world@2a937bb6772742ba97d9346ed8bcf6b8
```

**Comment by nhammond** [comment]
Fixed by PR #414. DataObjects are now a single model. If there is a failure when creating a FileResource, it triggers cleanup of the DataObject that was just created.
