### ISSUE TITLE
Step freezes with status "saving outputs"

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#262]
This happens consistently on speedseq_100k test during speedseq_alignment step. For example 2017-01-04 04:00:04
speedseq_100K (MainThread), https://104.197.217.121/stats/

**Comment by nhammond** [comment]
worker.log from the speedseq_alignment worker indicates that this is a timeout.

ERROR [2017-01-04 20:15:38,858] Traceback (most recent call last):
ERROR [2017-01-04 20:15:38,858]   File "/opt/loom-env/bin/loom-taskrunner", line 11, in <module>
ERROR [2017-01-04 20:15:38,858] load_entry_point('loomengine', 'console_scripts', 'loom-taskrunner')()
ERROR [2017-01-04 20:15:38,859]   File "/opt/loom/loomengine/worker/task_runner.py", line 524, in main
ERROR [2017-01-04 20:15:38,859] raise cleanup_error
ERROR [2017-01-04 20:15:38,859] loomengine.utils.exceptions
ERROR [2017-01-04 20:15:38,859] .
ERROR [2017-01-04 20:15:38,859] BadResponseError
ERROR [2017-01-04 20:15:38,859] :
ERROR [2017-01-04 20:15:38,859] 504 Server Error: Gateway Time-out for url: https://jenkins-speed-seq-100k-loom-srvr-jan-04-2017-120010:443/api/task-run-attempts/9e2957f51a414631b9a5c327bf2c60aa/
ERROR [2017-01-04 20:15:38,859] <html>
ERROR [2017-01-04 20:15:38,859] <head><title>504 Gateway Time-out</title></head>
ERROR [2017-01-04 20:15:38,859] <body bgcolor="white">
ERROR [2017-01-04 20:15:38,859] <center><h1>504 Gateway Time-out</h1></center>
ERROR [2017-01-04 20:15:38,859] <hr><center>nginx/1.10.2</center>
ERROR [2017-01-04 20:15:38,859] </body>
ERROR [2017-01-04 20:15:38,859] </html>

**Comment by nhammond** [comment]
Closing ticket since timeout behavior will change in release 0.3.0
