### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'chunk_size'

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#266]
User reported this error. I was able to reproduce it by running "loom file import" on a gs:// file that does not exist:

```
(loom-env) 14799:loom s0198839$ loom import file gs://storage-public-data/references/hg19/chr22/chr22.f
Traceback (most recent call last):
  File "/Users/s0198839/dev/loom/loom-env/bin/loom", line 11, in <module>
    load_entry_point('loomengine', 'console_scripts', 'loom')()
  File "/Users/s0198839/dev/loom/loom/loomengine/client/main.py", line 72, in main
    return Main().run()
  File "/Users/s0198839/dev/loom/loom/loomengine/client/main.py", line 68, in run
    return self.args.SubcommandClass(self.args).run()
  File "/Users/s0198839/dev/loom/loom/loomengine/client/importer.py", line 136, in run
    self.args.SubSubcommandClass(self.args).run()
  File "/Users/s0198839/dev/loom/loom/loomengine/client/importer.py", line 46, in run
    self.args.note
  File "/Users/s0198839/dev/loom/loom/loomengine/utils/filemanager.py", line 457, in import_from_patterns
    files.extend(self.import_from_pattern(pattern, note))
  File "/Users/s0198839/dev/loom/loom/loomengine/utils/filemanager.py", line 462, in import_from_pattern
    for source in SourceSet(pattern, self.settings):
  File "/Users/s0198839/dev/loom/loom/loomengine/utils/filemanager.py", line 43, in SourceSet
    return GoogleStorageSourceSet(pattern, settings)
  File "/Users/s0198839/dev/loom/loom/loomengine/utils/filemanager.py", line 97, in __init__
    self.sources = [GoogleStorageSource(pattern, settings)]
  File "/Users/s0198839/dev/loom/loom/loomengine/utils/filemanager.py", line 207, in __init__
    self.blob.chunk_size = self.CHUNK_SIZE
AttributeError: 'NoneType' object has no attribute 'chunk_size'
```

**Comment by nhammond** [comment]
Better error message added in b76c59d358bb55b550e32d2fbbaf428dc6e8508b
