### ISSUE TITLE
Loom client ignores "gcloud auth activate-service-account" credentials

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#267]
1) On a VM with no bucket write privileges, with a service account JSON key file that does have bucket write privileges
2) Run "gcloud auth activate-service-account"
3) Run "loom import file ...". This fails with insufficient privileges.
4) Run "gsutil cp ...". This succeeds, using the service account privileges.

(loom-env) [s0198839@loom-client-2017-02-03 ~]$ gcloud auth activate-service-account webservices@cgsdevelopment-1216.iam.gserviceaccount.com --key-file CGSDevelopment-a1f1baed4479.json 
Activated service account credentials for: [webservices@cgsdevelopment-1216.iam.gserviceaccount.com]
(loom-env) [s0198839@loom-client-2017-02-03 ~]$ loom import files loom/doc/examples/hello_world/*.txt
Importing file from file:///home/s0198839/loom/doc/examples/hello_world/hello.txt...
   calculating md5 hash...
   copying to destination gs://cgsdevelopment-1216-loom/root/loomdata/imported/20170203193705-6bdc609d1cac4d08a54bca61bbc12dd3-hello.txt...
Traceback (most recent call last):
  File "/home/s0198839/loom-env/bin/loom", line 11, in <module>
    load_entry_point('loomengine', 'console_scripts', 'loom')()
  File "/home/s0198839/loom/loomengine/client/main.py", line 72, in main
    return Main().run()
  File "/home/s0198839/loom/loomengine/client/main.py", line 68, in run
    return self.args.SubcommandClass(self.args).run()
  File "/home/s0198839/loom/loomengine/client/importer.py", line 136, in run
    self.args.SubSubcommandClass(self.args).run()
  File "/home/s0198839/loom/loomengine/client/importer.py", line 46, in run
    self.args.note
  File "/home/s0198839/loom/loomengine/utils/filemanager.py", line 459, in import_from_patterns
    files.extend(self.import_from_pattern(pattern, note))
  File "/home/s0198839/loom/loomengine/utils/filemanager.py", line 467, in import_from_pattern
    note
  File "/home/s0198839/loom/loomengine/utils/filemanager.py", line 474, in import_file
    source_url
  File "/home/s0198839/loom/loomengine/utils/filemanager.py", line 543, in _execute_file_import
    source.copy_to(destination)
  File "/home/s0198839/loom/loomengine/utils/filemanager.py", line 134, in copy_to
    copier.copy()
  File "/home/s0198839/loom/loomengine/utils/filemanager.py", line 425, in copy
    self.destination.blob.upload_from_filename(self.source.get_path())
  File "/home/s0198839/loom-env/lib/python2.7/site-packages/gcloud/storage/blob.py", line 597, in upload_from_filename
    encryption_key=encryption_key, client=client)
  File "/home/s0198839/loom-env/lib/python2.7/site-packages/gcloud/storage/blob.py", line 548, in upload_from_file
    self._check_response_error(request, http_response)
  File "/home/s0198839/loom-env/lib/python2.7/site-packages/gcloud/storage/blob.py", line 402, in _check_response_error
    error_info=request.url)
gcloud.exceptions.Forbidden: 403 Insufficient Permission (https://www.googleapis.com/upload/storage/v1/b/cgsdevelopment-1216-loom/o?uploadType=media&name=root%2Floomdata%2Fimported%2F20170203193705-6bdc609d1cac4d08a54bca61bbc12dd3-hello.txt)

(loom-env) [s0198839@loom-client-2017-02-03 ~]$ gsutil cp loom/doc/examples/hello_world/hello.txt gs://cgsdevelopment-1216-loom/root/loomdata/imported/20170203193705-6bdc609d1cac4d08a54bca61bbc12dd3-hello.txt

**Comment by nhammond** [comment]
This can be resolved by assigning the service account directly to the VM. That doesn't cover every use case but it handles our needs for now. The long-term solution is to remove dependency on google cloud authorization for workflow management. Should use signed URLs issued by the server instead, or post to the server directly.
