### ISSUE TITLE
User can launch a gcloud server then must set GOOGLE_APPLICATION_CREDENTIALS to connect

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#278]
(venv) 14799:loomengine s0198839$ loom test integration
Calculating md5 on file "file:///Users/s0198839/dev/loom-development/loom/loomengine/client/test/templates/message.txt"...
Importing file from file:///Users/s0198839/dev/loom-development/loom/loomengine/client/test/templates/message.txt...
kTraceback (most recent call last):
  File "/Users/s0198839/dev/loom-development/venv/bin/loom", line 11, in <module>
    load_entry_point('loomengine', 'console_scripts', 'loom')()
  File "/Users/s0198839/dev/loom-development/loom/loomengine/client/main.py", line 72, in main
    return Main().run()
  File "/Users/s0198839/dev/loom-development/loom/loomengine/client/main.py", line 68, in run
    return self.args.SubcommandClass(self.args).run()
  File "/Users/s0198839/dev/loom-development/loom/loomengine/client/importer.py", line 156, in run
    self.args.SubSubcommandClass(self.args).run()
  File "/Users/s0198839/dev/loom-development/loom/loomengine/client/importer.py", line 46, in run
    force_duplicates=self.args.force_duplicates,
  File "/Users/s0198839/dev/loom-development/loom/loomengine/utils/filemanager.py", line 449, in import_from_patterns
    pattern, note, force_duplicates=force_duplicates))
  File "/Users/s0198839/dev/loom-development/loom/loomengine/utils/filemanager.py", line 458, in import_from_pattern
    force_duplicates=force_duplicates
  File "/Users/s0198839/dev/loom-development/loom/loomengine/utils/filemanager.py", line 466, in import_file
    source_url,
  File "/Users/s0198839/dev/loom-development/loom/loomengine/utils/filemanager.py", line 577, in _execute_file_import
    raise e
oauth2client.client.ApplicationDefaultCredentialsError: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
ERROR: Failed to import file.

**Comment by isaacliao** [comment]
Possibly related: https://github.com/StanfordBioinformatics/loom/issues/242

**Comment by nhammond** [comment]
@isaacliao , this error message seems clear and is consistent with what I am seeing--no application default credentials on my laptop unless I set GOOGLE_APPLICATION_CREDENTIALS env variable.

> oauth2client.client.ApplicationDefaultCredentialsError: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.

My only doubt is that you haven't been able to reproduce the error. Can you run this on your laptop to confirm that?

```
# Connect to VPN, then:
unset GOOGLE_APPLICATION_CREDENTIALS
loom server connect https://104.198.159.22:443
loom import file some_local_file.dat
```

**Comment by nhammond** [comment]
Maybe this explains our difference in state:
```gcloud auth application-default login```

which creates a file here:
```~/.config/gcloud/application_default_credentials.json```

**Comment by nhammond** [comment]
Updated error messages with instructions for setting application default credentials in efd753db6152a15f7e7f6bf7d8c477e056a76311
