### ISSUE TITLE
TaskAttempts fail with broken pipe error

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#322]
A single run of hello_world workflow works. But when submitting 10 runs immediately one after the other, I start to see errors like this in the "worker" container, and all the runs fail:
```
[2017-03-21 17:27:46,718: CRITICAL/MainProcess] Couldn't ack 59, reason:error(32, 'Broken pipe')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/kombu/message.py", line 130, in ack_log_error
    self.ack(multiple=multiple)
  File "/usr/local/lib/python2.7/dist-packages/kombu/message.py", line 125, in ack
    self.channel.basic_ack(self.delivery_tag, multiple=multiple)
  File "/usr/local/lib/python2.7/dist-packages/amqp/channel.py", line 1408, in basic_ack
    spec.Basic.Ack, argsig, (delivery_tag, multiple),
  File "/usr/local/lib/python2.7/dist-packages/amqp/abstract_channel.py", line 64, in send_method
    conn.frame_writer(1, self.channel_id, sig, args, content)
  File "/usr/local/lib/python2.7/dist-packages/amqp/method_framing.py", line 174, in write_frame
    write(view[:offset])
  File "/usr/local/lib/python2.7/dist-packages/amqp/transport.py", line 269, in write
    self._write(s)
  File "/usr/local/lib/python2.7/dist-packages/eventlet/greenio/base.py", line 390, in sendall
    tail = self.send(data, flags)
  File "/usr/local/lib/python2.7/dist-packages/eventlet/greenio/base.py", line 384, in send
    return self._send_loop(self.fd.send, data, flags)
  File "/usr/local/lib/python2.7/dist-packages/eventlet/greenio/base.py", line 371, in _send_loop
    return send_method(data, *args)
error: [Errno 32] Broken pipe
```

**Comment by nhammond** [comment]
Using same test (10 runs of hello_world on local with CloudSQL database). Tried upgraded from Celery 4.0.0 to 4.0.2. Still seeing lots of broken pipe errors in the logs

```
[2017-03-22 22:01:52,884: CRITICAL/MainProcess] Couldn't ack 66, reason:error(32, 'Broken pipe')
error: [Errno 32] Broken pipe
```

**Comment by nhammond** [comment]
Resolved by setting CELERY_BROKER_POOL_LIMIT = None (no limit). Default was 10. bc21072033c7023e89110fdf2c10522d1f79d94b

Able to run 10 hello_world runs with CloudSQL database as described above, with all completing successfully.
