### ISSUE TITLE
Large file import fails in google storage -> google storage

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#333]
(loom-env) [s0198839@cgs-demo-loom-client ~]$ loom import file gs://benchmarking-inputs/ucsc.hg19_chrRemoved.fasta
Calculating md5 on file "gs://benchmarking-inputs/ucsc.hg19_chrRemoved.fasta"...
Importing file from gs://benchmarking-inputs/ucsc.hg19_chrRemoved.fasta...
   copying to destination gs://cgs-demo-samples/loom-data/imported/2017-03-30T23.37.21Z_8e11336e_ucsc.hg19_chrRemoved.fasta ...
Traceback (most recent call last):
  File "/home/s0198839/loom-env/bin/loom", line 9, in <module>
    load_entry_point('loomengine==0.3.1', 'console_scripts', 'loom')()
  File "/home/s0198839/loom/loomengine/client/main.py", line 89, in main
    return Main().run()
  File "/home/s0198839/loom/loomengine/client/main.py", line 85, in run
    return self.args.SubcommandClass(self.args).run()
  File "/home/s0198839/loom/loomengine/client/importer.py", line 160, in run
    self.args.SubSubcommandClass(self.args).run()
  File "/home/s0198839/loom/loomengine/client/importer.py", line 47, in run
    force_duplicates=self.args.force_duplicates,
  File "/home/s0198839/loom/loomengine/utils/filemanager.py", line 454, in import_from_patterns
    pattern, note, force_duplicates=force_duplicates))
  File "/home/s0198839/loom/loomengine/utils/filemanager.py", line 463, in import_from_pattern
    force_duplicates=force_duplicates
  File "/home/s0198839/loom/loomengine/utils/filemanager.py", line 471, in import_file
    source_url,
  File "/home/s0198839/loom/loomengine/utils/filemanager.py", line 586, in _execute_file_import
    raise e
gcloud.exceptions.GCloudError: 413 Copy spanning locations and/or storage classes could not complete within 30 seconds. Please use the Rewrite method (https://cloud.google.com/storage/docs/json_api/v1/objects/rewrite) instead. (POST https://www.googleapis.com/storage/v1/b/benchmarking-inputs/o/ucsc.hg19_chrRemoved.fasta/copyTo/b/cgs-demo-samples/o/loom-data%2Fimported%2F2017-03-30T23.37.21Z_8e11336e_ucsc.hg19_chrRemoved.fasta)

**Comment by nhammond** [comment]
There is wide variability on the time for bucket-to-bucket transfers, ranging from a few seconds to a few minutes for a ~3 GB file. We see faster times for transfers between regional buckets in the same region. Transfers between Multiregional buckets span the gamut from 2s to 4m. We don't know why. But when the copy operation is slower than 30 seconds, the above error will occur.

The solution was to use Google's "storage.Blob.rewrite" function instead of "storage.Blob.copy_blob". That was only available on recent library versions, so we upgraded from gcloud 0.18.3 (which appears to be stale) to google-cloud 0.25.0.

Fixed with 537bec0fea1676de3cd17c8e11a8e44041011b4b
