### ISSUE TITLE
sporadic failure in gce.py ansible inventory script

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#349]
We had a test fail with this error reported in a timepoint on one of the TaskAttempts:

```
No config file found; using defaults\nERROR! Attempted to execute \"/loom-settings/inventory/gce_wrapper.py\" as inventory script:
…
raise e\nssl.SSLError: ('The read operation timed out',)\
…
```

However, I ran the inventory script interactively in the loom-master container on the Google Cloud VM, using the existing environment variables, and it ran without errors. Appears to be sporadic.

**Comment by nhammond** [comment]
Another version of failure in the gce.py script:

No config file found; using defaults Traceback (most recent call last): File "/loom-settings/inventory/gce.py", line 476, in <module> GceInventory() File "/loom-settings/inventory/gce.py", line 176, in __init__ self.do_api_calls_update_cache() File "/loom-settings/inventory/gce.py", line 389, in do_api_calls_update_cache data = self.group_instances(zones) File "/loom-settings/inventory/gce.py", line 408, in group_instances for node in self.list_nodes(): File "/loom-settings/inventory/gce.py", line 398, in list_nodes all_nodes.extend(self.driver.list_nodes()) File "/usr/local/lib/python2.7/dist-packages/libcloud/compute/drivers/gce.py", line 2307, in list_nodes list_nodes.append(self._to_node(i)) File "/usr/local/lib/python2.7/dist-packages/libcloud/compute/drivers/gce.py", line 8125, in _to_node extra['boot_disk'] = self.ex_get_volume(bd['name'], bd['zone']) File "/usr/local/lib/python2.7/dist-packages/libcloud/compute/drivers/gce.py", line 6950, in ex_get_volume response = self.connection.request(request, method='GET').object File "/usr/local/lib/python2.7/dist-packages/libcloud/compute/drivers/gce.py", line 120, in request response = super(GCEConnection, self).request(*args, **kwargs) File "/usr/local/lib/python2.7/dist-packages/libcloud/common/google.py", line 812, in request raise e ssl.SSLError: ('The read operation timed out',) ERROR! Attempted to execute "/loom-settings/inventory/gce_wrapper.py" as inventory script: failed to parse executable inventory script results from /loom-settings/inventory/gce_wrapper.py: Syntax Error while loading YAML. The error appears to have been in '<string>': line 3, column 1, but may be elsewhere in the file depending on the exact syntax problem.

**Comment by nhammond** [comment]
Retry gce.py if output is not valid JSON. b95eaf63c4735e39238628ff31d7b9a0f9062747
