### ISSUE TITLE
Loom show files breaks if 'import' field is not valid json

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#357]
This represents 2 failures: the model was not properly validated, and the client is not robust to handle flawed data. If the client errors on one record, it should still be able to render the remaining records.

```
(env) 14799:loom s0198839$ loom show files --detail
[showing 33 files]
...

Traceback (most recent call last):
  File "/Users/s0198839/dev/loom/env/bin/loom", line 9, in <module>
    load_entry_point('loomengine==0.3.2', 'console_scripts', 'loom')()
  File "/Users/s0198839/dev/loom/loom/loomengine/client/main.py", line 89, in main
    return Main().run()
  File "/Users/s0198839/dev/loom/loom/loomengine/client/main.py", line 85, in run
    return self.args.SubcommandClass(self.args).run()
  File "/Users/s0198839/dev/loom/loom/loomengine/client/show.py", line 285, in run
    self.args.SubSubcommandClass(self.args).run()
  File "/Users/s0198839/dev/loom/loom/loomengine/client/show.py", line 68, in run
    self._show_files()
  File "/Users/s0198839/dev/loom/loom/loomengine/client/show.py", line 81, in _show_files
    text = self._render_file(file_data_object)
  File "/Users/s0198839/dev/loom/loom/loomengine/client/show.py", line 99, in _render_file
    if file_data_object['file_import'].get('source_url'):
```

Object retrieved from the API looks like this:
```
{
    "uuid": "bb95af9e-c2fa-4ea7-b616-eead91870a4d",
    "url": "https://35.188.85.246:443/api/data-files/bb95af9e-c2fa-4ea7-b616-eead91870a4d/",
    "file_resource": {
        "uuid": "c76e4bc7-9093-4b04-97d2-125e19714a18",
        "url": "https://35.188.85.246:443/api/file-resources/c76e4bc7-9093-4b04-97d2-125e19714a18/",
        "datetime_created": "2017-05-01T21:07:08.116009Z",
        "file_url": "gs://storage-demo/SCGV1-02/personalis-20170501/import-files/FASTQ/SCGV1-02_reads2.fastq.gz",
        "md5": "y+rjapVlAiqksmO3hZuW8g==",
        "upload_status": "complete"
    },
    "file_import": "imported",
    "type": "file",
    "is_array": false,
    "datetime_created": "2017-05-01 21:07:08.122400+00:00",
    "filename": "SCGV1-02_reads2.fastq.gz",
    "md5": "y+rjapVlAiqksmO3hZuW8g==",
    "source_type": "imported"
}
```

**Comment by nhammond** [comment]
Fixed in 629856c922ba9142e3b259ccb3cd00c70e799dfc
