### ISSUE TITLE
Error uploading file when multiple files on Loom server share the file name

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#36]
When running a workflow and assigning an input, if the value matches a file on the local path, this should take precedence over a file of the same name stored on the server. This works if there is only one file with a matching name. But if there is more than one file, currently Loom throws an error.
```
loom upload hello.txt
# uploads file
loom upload hello.txt #with different contents
# uploads file
loom run workflow.json
"hello": "Enter the hello file"
This input is required. Enter a file path or identifier.
> hello.txt
This input is required. Enter a file path or identifier.
> a.txt
Traceback (most recent call last):
  File "/Users/nhammond/work/loom/env/bin/loom", line 9, in <module>
    load_entry_point('loomengine', 'console_scripts', 'loom')()
  File "/Users/nhammond/work/loom/loom/loom/client/main.py", line 72, in main
    Main().run()
  File "/Users/nhammond/work/loom/loom/loom/client/main.py", line 68, in run
    self.args.SubcommandClass(self.args).run()
  File "/Users/nhammond/work/loom/loom/loom/client/run.py", line 290, in run
    self._prompt_for_missing_inputs()
  File "/Users/nhammond/work/loom/loom/loom/client/run.py", line 467, in _prompt_for_missing_inputs
    ).prompt_for_input(input_name, input['prompt'])
  File "/Users/nhammond/work/loom/loom/loom/client/run.py", line 91, in prompt_for_input
    data_object = self._get_input(input_id)
  File "/Users/nhammond/work/loom/loom/loom/client/run.py", line 54, in _get_input
    input_from_server = self._get_input_from_server(input_id)
  File "/Users/nhammond/work/loom/loom/loom/client/run.py", line 70, in _get_input_from_server
    data_object_list = self.objecthandler.get_file_data_object_index(query_string=input_id, max=1)
  File "/Users/nhammond/work/loom/loom/loom/common/objecthandler.py", line 92, in get_file_data_object_index
    raise IdMatchedTooManyFileDataObjectsError('Found %s File Data Objects, expected at most %s' %(len(file_data_objects), max))
loom.common.exceptions.IdMatchedTooManyFileDataObjectsError: Found 2 File Data Objects, expected at most 1
```

**Comment by nhammond** [comment]
Fixed by a101abdd4b
