### ISSUE TITLE
"OSError Operation not supported" during file import

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#362]
loom import file gs://storage-public-data/WorkflowInputFiles/hg19/references/ucsc.hg19.fasta.fai

Calculating md5 on file "gs://storage-public-data/WorkflowInputFiles/hg19/references/ucsc.hg19.fasta.fai"...
Importing file from gs://storage-public-data/WorkflowInputFiles/hg19/references/ucsc.hg19.fasta.fai...
   copying to destination file:///home/s0198839/loom-data/imported/2017-05-03T20.26.51Z_ced32076_ucsc.hg19.fasta.fai ...
Traceback (most recent call last):
  File "/Users/s0198839/dev/loom/env/bin/loom", line 9, in <module>
    load_entry_point('loomengine==0.3.3', 'console_scripts', 'loom')()
  File "/Users/s0198839/dev/loom/loom/loomengine/client/main.py", line 89, in main
    return Main().run()
  File "/Users/s0198839/dev/loom/loom/loomengine/client/main.py", line 85, in run
    return self.args.SubcommandClass(self.args).run()
  File "/Users/s0198839/dev/loom/loom/loomengine/client/importer.py", line 160, in run
    self.args.SubSubcommandClass(self.args).run()
  File "/Users/s0198839/dev/loom/loom/loomengine/client/importer.py", line 47, in run
    force_duplicates=self.args.force_duplicates,
  File "/Users/s0198839/dev/loom/loom/loomengine/utils/filemanager.py", line 463, in import_from_patterns
    pattern, note, force_duplicates=force_duplicates))
  File "/Users/s0198839/dev/loom/loom/loomengine/utils/filemanager.py", line 472, in import_from_pattern
    force_duplicates=force_duplicates
  File "/Users/s0198839/dev/loom/loom/loomengine/utils/filemanager.py", line 480, in import_file
    source_url,
  File "/Users/s0198839/dev/loom/loom/loomengine/utils/filemanager.py", line 596, in _execute_file_import
    raise e
OSError: [Errno 45] Operation not supported: '/home/s0198839'

**Comment by nhammond** [comment]
Unsupported use case. I started a local server on a google cloud VM, then connected from my laptop and attempted to do a file import. I clarified the error message with this commit: 4e6809d491977886a224f05edd2db81ceee79352
