### ISSUE TITLE
Error "'TaskAttempt' has no attribute 'get'" in server's worker log

### ISSUE THREAD

**Issue by isaacliao** [StanfordBioinformatics/loom#373]
```
[2017-05-05 00:17:48,974: INFO/MainProcess] Received task: api.async._kill_task_attempt[a6a24613-9e4b-4309-be03-62f19e93a780]
[2017-05-05 00:17:48,977: ERROR/MainProcess] Task api.async._kill_task_attempt[a6a24613-9e4b-4309-be03-62f19e93a780] raised unexpected: AttributeError("type object 'TaskAttempt' has no attribute 'get'",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 367, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 622, in __protected_call__
    return self.run(*args, **kwargs)
  File "/loomengine/loomengine/master/api/async.py", line 269, in _kill_task_attempt
    task_attempt = TaskAttempt.get(uuid=task_attempt_uuid)
AttributeError: type object 'TaskAttempt' has no attribute 'get'
```

**Comment by nhammond** [comment]
Fixed in e4894fdca47c2ad1778153392a7e1c1541c6a8ab
