### ISSUE TITLE
TaskAttempt fails saving logfiles: Stream is already exhausted

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#415]
This was encountered when running "integration_test" in a Google Cloud deployment. The error message saved in the TaskAttemptEvent follows. It comes just after "Saving logfiles".

"Saving logs failed with error Stream is already exhausted. There is no content remaining."

**Comment by nhammond** [comment]
Unable to reproduce with a Loom server on my laptop, after interactively calling _get_stdout, _get_stderr, _stderr_stream_worker, and _stream_docker_logs multiple times with no error.

One difference: the google cloud server uses LOOM_FLUENTD_OUTPUTS: "elasticsearch,google_cloud"

**Comment by nhammond** [comment]
No change from removing "google_cloud". Same error occurs.

**Comment by nhammond** [comment]
Root cause of failure is here, in Local2GoogleStorageCopier.copy():

self.destination.blob.upload_from_filename(self.source.get_path())
*** ValueError: Stream is already exhausted. There is no content remaining.

**Comment by nhammond** [comment]
In google-cloud 0.26.0:

```
import google.cloud.storage
client = google.cloud.storage.client.Client('gbsc-gcp-project-scgs-dev')
bucket = client.get_bucket('gbsc-gcp-project-scgs-dev-user-nhammond')
blob = google.cloud.storage.blob.Blob('test_upload_empty_file', bucket, chunk_size=1024*1024*100)
blob.upload_from_filename('/Users/s0xxxxxx/empty.txt')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/s0xxxxxx/dev/loom-release/env/lib/python2.7/site-packages/google/cloud/storage/blob.py", line 934, in upload_from_filename
    size=total_bytes)
  File "/Users/s0xxxxxx/dev/loom-release/env/lib/python2.7/site-packages/google/cloud/storage/blob.py", line 891, in upload_from_file
    client, file_obj, content_type, size, num_retries)
  File "/Users/s0xxxxxx/dev/loom-release/env/lib/python2.7/site-packages/google/cloud/storage/blob.py", line 818, in _do_upload
    client, stream, content_type, size, num_retries)
  File "/Users/s0xxxxxx/dev/loom-release/env/lib/python2.7/site-packages/google/cloud/storage/blob.py", line 771, in _do_resumable_upload
    response = upload.transmit_next_chunk(transport)
  File "/Users/s0xxxxxx/dev/loom-release/env/lib/python2.7/site-packages/google/resumable_media/requests/upload.py", line 392, in transmit_next_chunk
    method, url, payload, headers = self._prepare_request()
  File "/Users/s0xxxxxx/dev/loom-release/env/lib/python2.7/site-packages/google/resumable_media/_upload.py", line 531, in _prepare_request
    self._stream, self._chunk_size, self._total_bytes)
  File "/Users/s0xxxxxx/dev/loom-release/env/lib/python2.7/site-packages/google/resumable_media/_upload.py", line 805, in get_next_chunk
    u'Stream is already exhausted. There is no content remaining.')
ValueError: Stream is already exhausted. There is no content remaining.
```

**Comment by nhammond** [comment]
Succeeds in google-cloud 0.23.0.

There is an open ticket for this:
https://github.com/GoogleCloudPlatform/google-cloud-python/issues/3577

**Comment by nhammond** [comment]
rolled back google-cloud version in 260d1047ae1bcba1737f229c00d93b41e2bbb2de
