### ISSUE TITLE
Export files from google storage fails to retry when service not available

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#439]
Logged by the TaskMonitor:

```
Copying inputs failed. Traceback (most recent call last): File "/loomengine/loomengine/worker/task_monitor.py", line 142, in _copy_inputs TaskAttemptInput(input, self).copy() File "/loomengine/loomengine/worker/inputs.py", line 19, in copy retry=True) File "/loomengine/loomengine/utils/filemanager.py", line 768, in export_file Source(source_url, self.settings, retry=retry).copy_to(destination) File "/loomengine/loomengine/utils/filemanager.py", line 145, in copy_to copier.copy() File "/loomengine/loomengine/utils/filemanager.py", line 478, in copy 'File download') File "/loomengine/loomengine/utils/__init__.py", line 28, in execute_with_retries return retriable_function() File "/loomengine/loomengine/utils/filemanager.py", line 475, in <lambda> self.destination.get_path()), File "/usr/local/lib/python2.7/dist-packages/google/cloud/storage/blob.py", line 387, in download_to_filename self.download_to_file(file_obj, client=client) File "/usr/local/lib/python2.7/dist-packages/google/cloud/storage/blob.py", line 371, in download_to_file download.initialize_download(request, client._base_connection.http) File "/usr/local/lib/python2.7/dist-packages/google/cloud/streaming/transfer.py", line 390, in initialize_download self.stream_file(use_chunks=True, headers=http_request.headers) File "/usr/local/lib/python2.7/dist-packages/google/cloud/streaming/transfer.py", line 617, in stream_file headers=headers) File "/usr/local/lib/python2.7/dist-packages/google/cloud/streaming/transfer.py", line 509, in _get_chunk self.bytes_http, request, retries=self.num_retries) File "/usr/local/lib/python2.7/dist-packages/google/cloud/streaming/http_wrapper.py", line 384, in make_api_request redirections=redirections) File "/usr/local/lib/python2.7/dist-packages/google/cloud/streaming/http_wrapper.py", line 353, in _make_api_request_no_retry _check_response(response) File "/usr/local/lib/python2.7/dist-packages/google/cloud/streaming/http_wrapper.py", line 287, in _check_response raise BadStatusCodeError.from_response(response) BadStatusCodeError: HttpError accessing <https://www.googleapis.com/download/storage/v1/b/cgsdevelopment-gcp-project-scgs-dev-loom/o/loom-data%2Fimported%2F2017-07-28T19.15.09Z_85c89947_SCGV1-06_reads2.fastq.gz?generation=1501269310542987&alt=media>: response: <{'status': '503', 'x-goog-metageneration': '1', 'content-disposition': 'attachment', 'content-language': 'en', 'expires': 'Mon, 01 Jan 1990 00:00:00 GMT', 'vary': 'Origin, X-Origin', 'content-length': '19', 'server': 'UploadServer', 'content-range': 'bytes 2936012800-3040870399/3555310905', 'etag': 'CIup3v/XrNUCEAE=', 'x-goog-generation': '1501269310542987', 'pragma': 'no-cache', 'cache-control': 'no-cache, no-store, max-age=0, must-revalidate', 'date': 'Fri, 28 Jul 2017 19:30:41 GMT', 'content-type': 'text/plain; charset=utf-8', 'x-guploader-uploadid': 'AEnB2UrTQ4GMCBO218r9owmEJApsUd8_1_dxYfmR29_OgW50hWZ9rAZOYPysQrovcTKhSOKFpHS_Iu7yYLTTDN9VcmphK6i8Mg', 'x-goog-storage-class': 'STANDARD'}>, content <Service Unavailable>
```

**Comment by nhammond** [comment]
fixed in 39d4d8991d6d138d5ba304a6807ad04996524f30
