### ISSUE TITLE
Duplicate labels can be added to a single object, cannot be removed

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#445]
```
loom template label add integration_test display
loom template label add integration_test display
loom template label list
[showing 1 labels]
display (2)
loom template label remove integration_test display
Traceback (most recent call last):
  File "/Users/s0198839/dev/loom-release/env/bin/loom", line 9, in <module>
    load_entry_point('loomengine==0.5.1', 'console_scripts', 'loom')()
  File "/Users/s0198839/dev/loom-release/loom/loomengine/client/main.py", line 102, in main
    return Main().run()
  File "/Users/s0198839/dev/loom-release/loom/loomengine/client/main.py", line 98, in run
    return self.args.SubcommandClass(self.args).run()
  File "/Users/s0198839/dev/loom-release/loom/loomengine/client/template.py", line 337, in run
    self.args.SubSubcommandClass(self.args).run()
  File "/Users/s0198839/dev/loom-release/loom/loomengine/client/template_label.py", line 106, in run
    label = self.connection.remove_template_label(templates[0]['uuid'], label_data)
  File "/Users/s0198839/dev/loom-release/loom/loomengine/utils/connection.py", line 397, in remove_template_label
    'templates/%s/remove-label/' % template_id)
  File "/Users/s0198839/dev/loom-release/loom/loomengine/utils/connection.py", line 91, in _post_object
    return self._post(object_data, relative_url).json()
  File "/Users/s0198839/dev/loom-release/loom/loomengine/utils/connection.py", line 29, in _post
    lambda: requests.post(
  File "/Users/s0198839/dev/loom-release/loom/loomengine/utils/connection.py", line 80, in _make_request_to_server
    response.raise_for_status()
  File "/Users/s0198839/dev/loom-release/env/lib/python2.7/site-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://104.197.240.74:443/api/templates/6d7edb83-fb82-4f9d-9d51-9bbe00e51da0/remove-label/
```

**Comment by nhammond** [comment]
Fixed in 78c998cb628f46a8dda90c09cf52832b56877a9b
