### ISSUE TITLE
Error in "loom file list --detail"

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#452]
Using 0.5.2-prerelease-rc1

```
loom file list refseq_b37_allexonsplus2.sorted.merged.cleaned.bed --detail
[showing 1 files]
Traceback (most recent call last):
  File "/Users/s0198839/dev/loom/env/bin/loom", line 9, in <module>
    load_entry_point('loomengine==0.5.2', 'console_scripts', 'loom')()
  File "/Users/s0198839/dev/loom/loom/loomengine/client/main.py", line 87, in main
    return Main().run()
  File "/Users/s0198839/dev/loom/loom/loomengine/client/main.py", line 83, in run
    return self.args.SubcommandClass(self.args).run()
  File "/Users/s0198839/dev/loom/loom/loomengine/client/file_client.py", line 274, in run
    self.args.SubSubcommandClass(self.args).run()
  File "/Users/s0198839/dev/loom/loom/loomengine/client/file_client.py", line 178, in run
    self._list_files()
  File "/Users/s0198839/dev/loom/loom/loomengine/client/file_client.py", line 192, in _list_files
    text = self._render_file(file_data_object)
  File "/Users/s0198839/dev/loom/loom/loomengine/client/file_client.py", line 207, in _render_file
    _render_time(file_data_object['datetime_created'])
  File "/Users/s0198839/dev/loom/loom/loomengine/client/__init__.py", line 13, in _render_time
    time_gmt = dateutil.parser.parse(timestr)
AttributeError: 'module' object has no attribute 'parser'
```

**Comment by nhammond** [comment]
Fixed in 7e76f8bc611d137b8e75461f32eb93d43fc66eb7
