### ISSUE TITLE
Badly formatted --extra-setting values give confusing error

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#453]
```
loom server start -e loomengine/loom:0.5.2-prerelease-rc1
Traceback (most recent call last):
  File "/Users/s0198839/dev/loom/env/bin/loom", line 9, in <module>
    load_entry_point('loomengine==0.5.2', 'console_scripts', 'loom')()
  File "/Users/s0198839/dev/loom/loom/loomengine/client/main.py", line 87, in main
    return Main().run()
  File "/Users/s0198839/dev/loom/loom/loomengine/client/main.py", line 83, in run
    return self.args.SubcommandClass(self.args).run()
  File "/Users/s0198839/dev/loom/loom/loomengine/client/server.py", line 128, in start
    settings.update(self._get_server_settings())
  File "/Users/s0198839/dev/loom/loom/loomengine/client/server.py", line 433, in _get_server_settings
    settings = self._get_start_settings_from_args()
  File "/Users/s0198839/dev/loom/loom/loomengine/client/server.py", line 442, in _get_start_settings_from_args
    settings.update(self._parse_extra_settings(self.args.extra_settings))
  File "/Users/s0198839/dev/loom/loom/loomengine/client/server.py", line 482, in _parse_extra_settings
    (key, value) = setting.split('=', 1)
ValueError: need more than 1 value to unpack
```

**Comment by nhammond** [comment]
Fixed in f186f3a68651345e43b368c9102dd6e719c6fbc6
