### ISSUE TITLE
Poor handling of backend error on file import

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#456]
Should print user message and suggest --retry option. Also consider making the --retry option on by default.

```
Calculating md5 on file "gs://cgs-reference-bundle/b37/Resources/AJTriov3.3_HG002son_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-Solid-10X_CHROM1-22_v3.3_highconf_intersected_ACE3.bed"...
Importing file from gs://cgs-reference-bundle/b37/Resources/AJTriov3.3_HG002son_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-Solid-10X_CHROM1-22_v3.3_highconf_intersected_ACE3.bed...
   copying to destination gs://gbsc-gcp-project-scgs-dev-loom/loom-data/imported/2017-09-07T01.21.32Z_3270efc4_AJTriov3.3_HG002son_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-Solid-10X_CHROM1-22_v3.3_highconf_intersected_ACE3.bed ...
Traceback (most recent call last):
  File "/home/vankrish/loom-env/bin/loom", line 9, in <module>
    load_entry_point('loomengine==0.5.2', 'console_scripts', 'loom')()
  File "/home/vankrish/loom/loomengine/client/main.py", line 87, in main
    return Main().run()
  File "/home/vankrish/loom/loomengine/client/main.py", line 83, in run
    return self.args.SubcommandClass(self.args).run()
  File "/home/vankrish/loom/loomengine/client/file_client.py", line 274, in run
    self.args.SubSubcommandClass(self.args).run()
  File "/home/vankrish/loom/loomengine/client/file_client.py", line 67, in run
    retry=self.args.retry,
  File "/home/vankrish/loom/loomengine/utils/filemanager.py", line 505, in import_from_patterns
    force_duplicates=force_duplicates, retry=retry))
  File "/home/vankrish/loom/loomengine/utils/filemanager.py", line 517, in import_from_pattern
    retry=retry,
  File "/home/vankrish/loom/loomengine/utils/filemanager.py", line 532, in import_file
    return self._execute_file_import(data_object, source, retry=retry)
  File "/home/vankrish/loom/loomengine/utils/filemanager.py", line 704, in _execute_file_import
    source.copy_to(destination)
  File "/home/vankrish/loom/loomengine/utils/filemanager.py", line 142, in copy_to
    copier.copy()
  File "/home/vankrish/loom/loomengine/utils/filemanager.py", line 445, in copy
    self.source.blob, token=rewrite_token)
  File "/home/vankrish/loom-env/lib/python2.7/site-packages/google/cloud/storage/blob.py", line 1206, in rewrite
    _target_object=self)
  File "/home/vankrish/loom-env/lib/python2.7/site-packages/google/cloud/_http.py", line 303, in api_request
    error_info=method + ' ' + url)
google.cloud.exceptions.InternalServerError: 500 Backend Error (POST https://www.googleapis.com/storage/v1/b/cgs-reference-bundle/o/b37%2FResources%2FAJTriov3.3_HG002son_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-Solid-10X_CHROM1-22_v3.3_highconf_intersected_ACE3.bed/rewriteTo/b/gbsc-gcp-project-scgs-dev-loom/o/loom-data%2Fimported%2F2017-09-07T01.21.32Z_3270efc4_AJTriov3.3_HG002son_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-Solid-10X_CHROM1-22_v3.3_highconf_intersected_ACE3.bed)
```

**Comment by nhammond** [comment]
Fixed in ffae8154fa3fd3120701d641c7d213e676f59cfc
