### ISSUE TITLE
Deadlock found when trying to get lock

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#460]
I see this sporadic error over half the time, using with a MySQL database when concurrently running several commands that all require database access (./manage.py verify_data_node_creation & ./manage.py verify_data_node_creation & ./manage.py verify_data_node_creation & ./manage.py verify_data_node_creation &)

```
Traceback (most recent call last):
  File "./manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/s0198839/dev/loom-release/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/Users/s0198839/dev/loom-release/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/s0198839/dev/loom-release/env/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/s0198839/dev/loom-release/env/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/s0198839/dev/loom-release/loom/loomengine/master/api/management/commands/verify_data_node_creation.py", line 19, in handle
    self.create_and_verify_data_tree()
  File "/Users/s0198839/dev/loom-release/loom/loomengine/master/api/management/commands/verify_data_node_creation.py", line 63, in create_and_verify_data_tree
    tree1 = s1.save()
  File "/Users/s0198839/dev/loom-release/env/lib/python2.7/site-packages/rest_framework/serializers.py", line 214, in save
    self.instance = self.create(validated_data)
  File "/Users/s0198839/dev/loom-release/loom/loomengine/master/api/serializers/data_nodes.py", line 49, in create
    contents, type)
  File "/Users/s0198839/dev/loom-release/loom/loomengine/master/api/serializers/data_nodes.py", line 108, in _create_data_node_from_data_objects
    self._add_data_objects(data_node, contents, data_type)
  File "/Users/s0198839/dev/loom-release/loom/loomengine/master/api/serializers/data_nodes.py", line 114, in _add_data_objects
    data_node, contents, path, data_type)
  File "/Users/s0198839/dev/loom-release/loom/loomengine/master/api/serializers/data_nodes.py", line 152, in _extend_all_paths_and_add_data_at_leaves
    data_node, contents[i], path_i, data_type)
  File "/Users/s0198839/dev/loom-release/loom/loomengine/master/api/serializers/data_nodes.py", line 152, in _extend_all_paths_and_add_data_at_leaves
    data_node, contents[i], path_i, data_type)
  File "/Users/s0198839/dev/loom-release/loom/loomengine/master/api/serializers/data_nodes.py", line 152, in _extend_all_paths_and_add_data_at_leaves
    data_node, contents[i], path_i, data_type)
  File "/Users/s0198839/dev/loom-release/loom/loomengine/master/api/serializers/data_nodes.py", line 141, in _extend_all_paths_and_add_data_at_leaves
    data_node.add_data_object(path, data_object)
  File "/Users/s0198839/dev/loom-release/loom/loomengine/master/api/models/data_nodes.py", line 135, in add_data_object
    self._extend_to_data_path(data_path, leaf_data=data_object)
  File "/Users/s0198839/dev/loom-release/loom/loomengine/master/api/models/data_nodes.py", line 287, in _extend_to_data_path
    return child._extend_to_data_path(data_path, leaf_data=leaf_data)
  File "/Users/s0198839/dev/loom-release/loom/loomengine/master/api/models/data_nodes.py", line 287, in _extend_to_data_path
    return child._extend_to_data_path(data_path, leaf_data=leaf_data)
  File "/Users/s0198839/dev/loom-release/loom/loomengine/master/api/models/data_nodes.py", line 279, in _extend_to_data_path
    return self.add_leaf(index, leaf_data)
  File "/Users/s0198839/dev/loom-release/loom/loomengine/master/api/models/data_nodes.py", line 94, in add_leaf
    data_node.save()
  File "/Users/s0198839/dev/loom-release/env/lib/python2.7/site-packages/mptt/models.py", line 993, in save
    super(MPTTModel, self).save(*args, **kwargs)
  File "/Users/s0198839/dev/loom-release/loom/loomengine/master/api/models/base.py", line 142, in save
    super(BaseModel, self).save(*args, **kwargs)
  File "/Users/s0198839/dev/loom-release/env/lib/python2.7/site-packages/django/db/models/base.py", line 806, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/s0198839/dev/loom-release/env/lib/python2.7/site-packages/django/db/models/base.py", line 836, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/s0198839/dev/loom-release/env/lib/python2.7/site-packages/django/db/models/base.py", line 922, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/s0198839/dev/loom-release/env/lib/python2.7/site-packages/django/db/models/base.py", line 961, in _do_insert
    using=using, raw=raw)
  File "/Users/s0198839/dev/loom-release/env/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/s0198839/dev/loom-release/env/lib/python2.7/site-packages/django/db/models/query.py", line 1060, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/s0198839/dev/loom-release/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1099, in execute_sql
    cursor.execute(sql, params)
  File "/Users/s0198839/dev/loom-release/env/lib/python2.7/site-packages/django/db/backends/utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/s0198839/dev/loom-release/env/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/Users/s0198839/dev/loom-release/env/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/s0198839/dev/loom-release/env/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/Users/s0198839/dev/loom-release/env/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/Users/s0198839/dev/loom-release/env/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/Users/s0198839/dev/loom-release/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.OperationalError: (1213, 'Deadlock found when trying to get lock; try restarting transaction')
```

**Comment by nhammond** [comment]
https://code.djangoproject.com/ticket/21670

**Comment by nhammond** [comment]
Added retries under api.models.base.BaseModel.save for django.db.utils.OperationalError.
81ee49b9fd83dbdf54bba07715d446766b2fd7af
