### ISSUE TITLE
run import fails for run without nested steps

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#514]
Reproduction steps:

```
loom example export join_two_words
loom template import join_two_words/join_two_words.yaml
loom run start join_two_words
# after completion
loom run export join_two_words
# flush loom

(env) 14799:loom s0198839$ loom run import join_two_words.yaml
Importing run from "file:///Users/s0198839/dev/loom/join_two_words.yaml".
Calculating md5 on file "file:///Users/s0198839/dev/loom/join_two_words.yaml.dependencies/files/uuid_017ced4c-3d22-4b6d-bfb6-9ecda6f599f7/stderr.log"...
Importing file from file:///Users/s0198839/dev/loom/join_two_words.yaml.dependencies/files/uuid_017ced4c-3d22-4b6d-bfb6-9ecda6f599f7/stderr.log...
   copying to destination file:///Users/s0198839/loomdata/logs/stderr.log ...
   imported file stderr.log@017ced4c-3d22-4b6d-bfb6-9ecda6f599f7
Calculating md5 on file "file:///Users/s0198839/dev/loom/join_two_words.yaml.dependencies/files/uuid_5aecfca6-4251-47a6-83ac-473955f6c5d2/stdout.log"...
Importing file from file:///Users/s0198839/dev/loom/join_two_words.yaml.dependencies/files/uuid_5aecfca6-4251-47a6-83ac-473955f6c5d2/stdout.log...
   copying to destination file:///Users/s0198839/loomdata/logs/stdout.log ...
   imported file stdout.log@5aecfca6-4251-47a6-83ac-473955f6c5d2
Importing template from "file:///Users/s0198839/dev/loom/join_two_words.yaml.dependencies/templates/join_two_words.yaml".
Imported template "join_two_words@dcba5cea-e6ad-4dff-81a6-8f639c3dc10d".
Traceback (most recent call last):
  File "/Users/s0198839/dev/loom/env/bin/loom", line 9, in <module>
    load_entry_point('loomengine==0.6.0.dev2', 'console_scripts', 'loom')()
  File "/Users/s0198839/dev/loom/loom/client/loomengine/main.py", line 110, in main
    return Main().run()
  File "/Users/s0198839/dev/loom/loom/client/loomengine/main.py", line 106, in run
    return self.args.SubcommandClass(self.args).run()
  File "/Users/s0198839/dev/loom/loom/client/loomengine/run.py", line 730, in run
    self.args.SubSubcommandClass(self.args).run()
  File "/Users/s0198839/dev/loom/loom/client/loomengine/run.py", line 342, in run
    link_files=self.args.link_files)
  File "/Users/s0198839/dev/loom/loom/utils/loomengine_utils/import_manager.py", line 467, in import_run
    imported_run = self.connection.post_run(run)
  File "/Users/s0198839/dev/loom/loom/utils/loomengine_utils/connection.py", line 355, in post_run
    return self._post_resource(run, 'runs/')
  File "/Users/s0198839/dev/loom/loom/utils/loomengine_utils/connection.py", line 141, in _post_resource
    return self._post(object_data, relative_url).json()
  File "/Users/s0198839/dev/loom/loom/utils/loomengine_utils/connection.py", line 48, in _post
    lambda: requests.post(
  File "/Users/s0198839/dev/loom/loom/utils/loomengine_utils/connection.py", line 132, in _make_request_to_server
    raise ServerConnectionError(response.text)
loomengine_utils.connection.ServerConnectionError: {"tasks":[{"data_path":["This field is required."]}]}
```

**Comment by nhammond** [comment]
There error was from missing "data_path" field in posted Task. Only came up with non-nested runs, since DRF runs default validation only at the top level of nested objects. data_path will be blank for non-parallel data, and fields with blank values are pruned, so missing data_path field is expected. Relaxed requirement on TaskSerializer so data_path is not required. fbcdefc04afaa4b6711ca39ff1ed43d7ba898b42
