### ISSUE TITLE
Handle errors from loomengine_utils in client

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#524]
There are many instances where something like this happens. This should display an informational message with no traceback.

```
loom run tag x y
usage: loom run tag [-h] {add,remove,list} ...
loom run tag: error: invalid choice: 'x' (choose from 'add', 'remove', 'list')
(env) 14799:loom s0198839$ loom run tag add x y
Traceback (most recent call last):
  File "/Users/s0198839/dev/loom/env/bin/loom", line 9, in <module>
    load_entry_point('loomengine==0.0.0.dev0', 'console_scripts', 'loom')()
  File "/Users/s0198839/dev/loom/loom/client/loomengine/main.py", line 110, in main
    return Main().run()
  File "/Users/s0198839/dev/loom/loom/client/loomengine/main.py", line 106, in run
    return self.args.SubcommandClass(self.args).run()
  File "/Users/s0198839/dev/loom/loom/client/loomengine/run.py", line 737, in run
    self.args.SubSubcommandClass(self.args).run()
  File "/Users/s0198839/dev/loom/loom/client/loomengine/run_tag.py", line 199, in run
    self.args.SubSubSubcommandClass(self.args).run()
  File "/Users/s0198839/dev/loom/loom/client/loomengine/run_tag.py", line 57, in run
    query_string=self.args.target)
  File "/Users/s0198839/dev/loom/loom/utils/loomengine_utils/connection.py", line 378, in get_run_index
    self._check_min_max(runs, 'Runs', min, max)
  File "/Users/s0198839/dev/loom/loom/utils/loomengine_utils/connection.py", line 204, in _check_min_max
    % (len(resources), label, min))
loomengine_utils.connection.ResourceCountError: Found 0 Runs, expected at least 1
```

**Comment by nhammond** [comment]
Fixed in 1a14343aad7511bbe1b9d3290f53acb316487dc3
