### ISSUE TITLE
client should prompt for login on 403 errors 

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#526]
loom test integration
Traceback (most recent call last):
  File "/Users/s0198839/dev/loom/env/bin/loom", line 9, in <module>
    load_entry_point('loomengine===shortlist', 'console_scripts', 'loom')()
  File "/Users/s0198839/dev/loom/loom/client/loomengine/main.py", line 115, in main
    return Main().run()
  File "/Users/s0198839/dev/loom/loom/client/loomengine/main.py", line 111, in run
    return self.args.SubcommandClass(self.args).run()
  File "/Users/s0198839/dev/loom/loom/client/loomengine/file_client.py", line 431, in run
    self.args.SubSubcommandClass(self.args).run()
  File "/Users/s0198839/dev/loom/loom/client/loomengine/file_client.py", line 30, in __init__
    self.export_manager = ExportManager(connection=self.connection)
  File "/Users/s0198839/dev/loom/loom/utils/loomengine_utils/export_manager.py", line 18, in __init__
    storage_settings = connection.get_storage_settings()
  File "/Users/s0198839/dev/loom/loom/utils/loomengine_utils/connection.py", line 564, in get_storage_settings
    'storage-settings/'
  File "/Users/s0198839/dev/loom/loom/utils/loomengine_utils/connection.py", line 172, in _get_resource
    response.raise_for_status()
  File "/Users/s0198839/dev/loom/env/lib/python2.7/site-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://35.232.236.124:443/api/storage-settings/
TEST FAILED: ERROR! Failed to import file.

**Comment by nhammond** [comment]
Added in 9badfddfda664669a4dfb9777975d0f24fdf6c8b
