### ISSUE TITLE
Running workflow by name raises error

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#53]
```
(env) DN525upg:~ nhammond$ loom run alignment_and_qc@f748f614adb53a
Traceback (most recent call last):
  File "/Users/nhammond/work/loom-demo/env/bin/loom", line 9, in <module>
load_entry_point('loomengine', 'console_scripts', 'loom')()
  File "/Users/nhammond/work/loom-demo/loom/loom/client/main.py", line 72, in main
Main().run()
  File "/Users/nhammond/work/loom-demo/loom/loom/client/main.py", line 68, in run
self.args.SubcommandClass(self.args).run()
  File "/Users/nhammond/work/loom-demo/loom/loom/client/run.py", line 286, in run
self._get_workflow()
  File "/Users/nhammond/work/loom-demo/loom/loom/client/run.py", line 326, in _get_workflow
workflow_from_file = self._get_workflow_from_file()
  File "/Users/nhammond/work/loom-demo/loom/loom/client/run.py", line 371, in _get_workflow_from_file
return WorkflowUploader.default_run(self.args.workflow)
  File "/Users/nhammond/work/loom-demo/loom/loom/client/upload.py", line 152, in default_run
return cls(args=args).run()
  File "/Users/nhammond/work/loom-demo/loom/loom/client/upload.py", line 141, in run
self.workflow = self.get_workflow(self.args.workflow)
  File "/Users/nhammond/work/loom-demo/loom/loom/client/upload.py", line 156, in get_workflow
workflow = read_as_json_or_yaml(workflow_file)
  File "/Users/nhammond/work/loom-demo/loom/loom/client/common.py", line 37, in read_as_json_or_yaml
raise NoFileError('Could not find or could not read file %s' % file)
loom.client.exceptions
.
NoFileError
:
Could not find or could not read file alignment_and_qc@f748f614adb53a
```

**Comment by nhammond** [comment]
Fixed with e3509837709b8103
