### ISSUE TITLE
finish_task_attempt fails with 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#560]
Version 0.7.1rc4

finish_task_attempt fails. Error observed in logs:

`
[2018-08-30 23:39:08,048: ERROR/MainProcess] Task api.async.finish_task_attempt[1332a508-df0a-437b-a490-dd41d36709f9] raised unexpected: TypeError("'NoneType' object is not iterable",)
`

From sentence_scoring workflow, split_into_letters step.

**Comment by nhammond** [comment]
`
ERROR [2018-08-31 01:41:30,948] Internal Server Error: /api/task-attempts/85bbd077-3f7b-4bcb-88c7-07750ecea4de/finish/
Traceback (most recent call last):
  File "/Users/s0198839/dev/loom/env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/s0198839/dev/loom/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/Users/s0198839/dev/loom/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/s0198839/dev/loom/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/s0198839/dev/loom/env/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/s0198839/dev/loom/env/lib/python2.7/site-packages/rest_framework/viewsets.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/s0198839/dev/loom/env/lib/python2.7/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/s0198839/dev/loom/env/lib/python2.7/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/s0198839/dev/loom/env/lib/python2.7/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/s0198839/dev/loom/loom/server/loomengine_server/api/views.py", line 324, in finish
    async.execute(async.finish_task_attempt, task_attempt.uuid)
  File "/Users/s0198839/dev/loom/loom/server/loomengine_server/api/async.py", line 33, in execute
    return task_function(*args, **kwargs)
  File "/Users/s0198839/dev/loom/env/lib/python2.7/site-packages/celery/local.py", line 191, in __call__
    return self._get_current_object()(*a, **kw)
  File "/Users/s0198839/dev/loom/env/lib/python2.7/site-packages/celery/app/task.py", line 375, in __call__
    return self.run(*args, **kwargs)
  File "/Users/s0198839/dev/loom/loom/server/loomengine_server/api/async.py", line 218, in finish_task_attempt
    task_attempt.finish()
  File "/Users/s0198839/dev/loom/loom/server/loomengine_server/api/models/task_attempts.py", line 119, in finish
    task.finish()
  File "/Users/s0198839/dev/loom/loom/server/loomengine_server/api/models/tasks.py", line 208, in finish
    self._push_all_outputs()
  File "/Users/s0198839/dev/loom/loom/server/loomengine_server/api/models/tasks.py", line 239, in _push_all_outputs
    self.run.push_all_outputs()
  File "/Users/s0198839/dev/loom/loom/server/loomengine_server/api/models/runs.py", line 244, in push_all_outputs
    run.push_all_inputs()
  File "/Users/s0198839/dev/loom/loom/server/loomengine_server/api/models/runs.py", line 226, in push_all_inputs
    = Task.create_unsaved_task_from_input_set(input_set, leaf)
TypeError: 'NoneType' object is not iterable
ERROR [2018-08-31 01:41:31,070] "POST /api/task-attempts/85bbd077-3f7b-4bcb-88c7-07750ecea4de/finish/ HTTP/1.1" 500 21291
`

**Comment by nhammond** [comment]
Fixed in ee57999e11b24e0e86350276c96c8a8fcfde4518
