### ISSUE TITLE
Outputs not pushed in sentence_scoring example

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#562]
In letter_to_integer step, after all 8 tasks have finished, the output data is incomplete:

`
[[73],[null,109],[null,null,null,null,116]]
 `

**Comment by nhammond** [comment]
`
t._push_all_outputs()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/s0198839/dev/loom/loom/server/loomengine_server/api/models/tasks.py", line 235, in _push_all_outputs
    attempt_output.data_node.clone(seed=output.data_node, save=False)
  File "/Users/s0198839/dev/loom/loom/server/loomengine_server/api/models/data_nodes.py", line 381, in clone
    assert clone.data_object is None, '"data_object" already set on DataNode clone target'
AssertionError: "data_object" already set on DataNode clone target
`

**Comment by nhammond** [comment]
Fixed in ef6359cbf67d172dc31122601d489821a0e12d1b
