### ISSUE TITLE
Errors in daemon log while webserver is still starting

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#61]
These errors occur because the daemon starts first and is unable to connect to the master, which is still starting. The error below appears repeatedly in the daemon log file:

INFO [2016-04-29 18:47:44,572] Running job queues
ERROR [2016-04-29 18:47:45,390] HTTPConnectionPool(host='10.128.0.2', port=80): 
Max retries exceeded with url: /api/controls/update/ (Caused by NewConnectionErr
or('<requests.packages.urllib3.connection.HTTPConnection object at 0x3b9ae50>: F
ailed to establish a new connection: [Errno 111] Connection refused',))
Traceback (most recent call last):
  File "/opt/loom/lib/python2.7/site-packages/loom/master/analysis/management/co
mmands/update_tasks.py", line 22, in handle
    response = requests.get(settings.MASTER_URL_FOR_WORKER+'/api/controls/update
/')
  File "/opt/loom/local/lib/python2.7/site-packages/requests/api.py", line 67, i
n get
    return request('get', url, params=params, **kwargs)
  File "/opt/loom/local/lib/python2.7/site-packages/requests/api.py", line 53, i
n request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/loom/local/lib/python2.7/site-packages/requests/sessions.py", line 
468, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/loom/local/lib/python2.7/site-packages/requests/sessions.py", line 
576, in send
    r = adapter.send(request, **kwargs)
  File "/opt/loom/local/lib/python2.7/site-packages/requests/adapters.py", line 
437, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='10.128.0.2', port=80): Max retries exc
eeded with url: /api/controls/update/ (Caused by NewConnectionError('<requests.p
ackages.urllib3.connection.HTTPConnection object at 0x3b9ae50>: Failed to establ
ish a new connection: [Errno 111] Connection refused',))
ERROR [2016-04-29 18:47:45,909] HTTPConnectionPool(host='10.128.0.2', port=80): 
Max retries exceeded with url: /api/controls/run/ (Caused by NewConnectionError(
'<requests.packages.urllib3.connection.HTTPConnection object at 0x29cedd0>: Fail
ed to establish a new connection: [Errno 111] Connection refused',))
Traceback (most recent call last):
  File "/opt/loom/lib/python2.7/site-packages/loom/master/analysis/management/co
mmands/run_tasks.py", line 22, in handle
    response = requests.get(settings.MASTER_URL_FOR_WORKER+'/api/controls/run/')
  File "/opt/loom/local/lib/python2.7/site-packages/requests/api.py", line 67, i
n get
    return request('get', url, params=params, **kwargs)
  File "/opt/loom/local/lib/python2.7/site-packages/requests/api.py", line 53, i
n request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/loom/local/lib/python2.7/site-packages/requests/sessions.py", line 
468, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/loom/local/lib/python2.7/site-packages/requests/sessions.py", line 
576, in send
    r = adapter.send(request, **kwargs)
  File "/opt/loom/local/lib/python2.7/site-packages/requests/adapters.py", line 
437, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='10.128.0.2', port=80): Max retries exc
eeded with url: /api/controls/run/ (Caused by NewConnectionError('<requests.pack
ages.urllib3.connection.HTTPConnection object at 0x29cedd0>: Failed to establish
 a new connection: [Errno 111] Connection refused',))

**Comment by nhammond** [comment]
Daemon has been removed.
