### ISSUE TITLE
Error when providing input inline with run command

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#83]
```
(env) DNab421257:hello_world nhammond$ loom run hello_world.json hello=hello.txt
Uploaded workflow hello_world@9c7fb9501661c7d6b7ecb32effaa2f3aca1765d82964971feaab5af17041b365
The input "%s" matches both a local file and one or more files on the server. Using the local file.

Enter a complete description of the data source "hello.txt". Provide enough detail to ensure traceability.
>

Uploading hello.txt ...
Created file source record hello.txt@e2971d1d4c307551e4ac6dfe3801838ee2d9537f505c3df459d2e756927dc609
Traceback (most recent call last):
  File "/Users/nhammond/work/loom/env/bin/loom", line 9, in <module>
load_entry_point('loomengine', 'console_scripts', 'loom')()
  File "/Users/nhammond/work/loom/loom/loom/client/main.py", line 77, in main
Main().run()
  File "/Users/nhammond/work/loom/loom/loom/client/main.py", line 73, in run
self.args.SubcommandClass(self.args).run()
  File "/Users/nhammond/work/loom/loom/loom/client/run.py", line 296, in run
self._create_workflow_run()
  File "/Users/nhammond/work/loom/loom/loom/client/run.py", line 479, in _create_workflow_run
workflow_run_from_server = self.objecthandler.post_workflow_run(self.workflow_run)
  File "/Users/nhammond/work/loom/loom/loom/common/objecthandler.py", line 158, in post_workflow_run
'workflow_runs/')
  File "/Users/nhammond/work/loom/loom/loom/common/objecthandler.py", line 39, in _post_object
return self._post(object_data, relative_url, raise_for_status=True).json()['object']
  File "/Users/nhammond/work/loom/loom/loom/common/objecthandler.py", line 17, in _post
return self._make_request_to_server(lambda: requests.post(url, data=json.dumps(data)), raise_for_status=raise_for_status)
  File "/Users/nhammond/work/loom/loom/loom/common/objecthandler.py", line 35, in _make_request_to_server
raise BadResponseError("%s\n%s" % (e.message, response.text))
loom.common.exceptions
.
BadResponseError
:
400 Client Error: BAD REQUEST for url: http://127.0.0.1:8000/api/workflow_runs/
{"message": "from_channel 'hello' is defined, but it has no source. There should be a corresponding workflow_input or a step_output with to_channel 'hello'"}
```

**Comment by nhammond** [comment]
Fixed with 5463052c372
