### ISSUE TITLE
django M2M relations are unique, silently refuse to add duplicates

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#94]
This is a problem if, for example, two of the same DataObject are entered into the queue on a channel. The second entry will not be added. The same behavior is seen with django-sortedm2m models.

**Comment by nhammond** [comment]
I tried a workaround using the "through" attribute on the m2m relation to work with the relation model directly. That breaks the "add" function, which raises an error when constructing the parent model in universalmodels.models. I modified universalmodels to catch the error and attempt to use the "through" model, assuming the related models are defined as fields 'parent' and 'child'. This got past the universalmodels error but caused the error below in sortedm2m. Apparently sortedm2m is not compatible with the "through" option.

======================================================================
ERROR: testChannelOutputModel (analysis.test.models.test_channels.TestChannel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/nhammond/work/loom/loom/loom/master/analysis/test/models/test_channels.py", line 12, in testChannelOutputModel
    self.roundTripJson(o)
  File "/Users/nhammond/work/loom/loom/loom/master/analysis/test/models/common.py", line 6, in roundTripJson
    model = cls.create(model.to_json())
  File "/Users/nhammond/work/loom/loom/loom/master/universalmodels/models.py", line 70, in to_json
    struct = self.to_struct()
  File "/Users/nhammond/work/loom/loom/loom/master/universalmodels/models.py", line 82, in to_struct
    field_struct = model.get_field_as_struct(field)
  File "/Users/nhammond/work/loom/loom/loom/master/universalmodels/models.py", line 488, in get_field_as_struct
    return self._get_x_to_many_field_as_struct(field)
  File "/Users/nhammond/work/loom/loom/loom/master/universalmodels/models.py", line 511, in _get_x_to_many_field_as_struct
    for model in related_model_list.iterator():
  File "/Users/nhammond/work/loom/env/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/nhammond/work/loom/env/lib/python2.7/site-packages/sortedm2m/fields.py", line 58, in get_queryset
    rel.through._sort_field_name,
AttributeError: type object 'ChannelOutputDataObject' has no attribute '_sort_field_name'

**Comment by nhammond** [comment]
The long-term solution is probably a custom-made ordered many to many relationship. I think that should be part of a bigger overhaul of universalmodels. For now, it looks like the error can be avoided by not using the same DataObject as two inputs in the same workflow.

**Comment by nhammond** [comment]
Another possibility is that if we are mindful of this behavior in the database design, it will not cause any problems. We should review the models to see if we have instances of OneToMany or ManyToMany models that can contain multiple relationships between the same two objects.

We have encountered the problem in 3 places so far. 1) A workflow contains multiple instances of the same step. With the current design that is forbidden anyway since channel names would collide. 2) Data objects queued in a channel. This design is likely to change in order to append indexes that are used to collate objects during merge steps. 3) A FileArray contains multiple instances of the same file. To be seen if this design can be reworked when we reintroduce FileArrays. We already have plans to abstract a DataObject from references to a DataObject so that provenance graphs do not cross over, and that may eliminate the need for Arrays to contain identical objects.

**Comment by nhammond** [comment]
Currently this causes an error any time multiple outputs of the same type are given for one step. The TaskDefinition object needs to be something like this:

{"command":"bwa index chr22.fa","environment":{"docker_image":"isaacliao/bwa-0.7.7"},"inputs":[{"data_object_content":{"filename":"chr22.fa","unnamed_file_content":{"hash_function":"md5","hash_value":"d90bc4f01813690544e9d746c925f03d"}},"type":"file"}],"outputs":[{"type":"file"},{"type":"file"},{"type":"file"},{"type":"file"},{"type":"file"}]} 

but it silently skips all but the first output:

{"command":"bwa index chr22.fa","environment":{"docker_image":"isaacliao/bwa-0.7.7"},"inputs":[{"data_object_content":{"filename":"chr22.fa","unnamed_file_content":{"hash_function":"md5","hash_value":"d90bc4f01813690544e9d746c925f03d"}},"type":"file"}],"outputs":[{"type":"file"}]}

That results in this error:

(env) timba:loom nhammond$ loom run ~/work/demo/workflows/alignment_and_qc_chr22.json
Importing workflow from file:///Users/nhammond/work/demo/workflows/alignment_and_qc_chr22.json...
...finished importing workflow alignment_and_qc@e19dcbed9bfa163bc6bcbd9317e8cfc71dc41b4cd06c9306f9c7172cb3c3cb4a
Traceback (most recent call last):
  File "/Users/nhammond/work/loom/env/bin/loom", line 9, in <module>
load_entry_point('loomengine', 'console_scripts', 'loom')()
  File "/Users/nhammond/work/loom/loom/loom/client/main.py", line 72, in main
Main().run()
  File "/Users/nhammond/work/loom/loom/loom/client/main.py", line 68, in run
self.args.SubcommandClass(self.args).run()
  File "/Users/nhammond/work/loom/loom/loom/client/run.py", line 64, in run
'inputs': inputs
  File "/Users/nhammond/work/loom/loom/loom/common/objecthandler.py", line 161, in post_run_request
'run-requests/')
  File "/Users/nhammond/work/loom/loom/loom/common/objecthandler.py", line 53, in _post_object
return self._post(object_data, relative_url, raise_for_status=True).json()['object']
  File "/Users/nhammond/work/loom/loom/loom/common/objecthandler.py", line 19, in _post
return self._make_request_to_server(lambda: requests.post(url, data=json.dumps(data)), raise_for_status=raise_for_status)
  File "/Users/nhammond/work/loom/loom/loom/common/objecthandler.py", line 50, in _make_request_to_server
raise error
loom.common.exceptions
.
BadResponseError
:
500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:8000/api/run-requests/
{"message": "The _id 4ee15f996ea3ae74f0515d54f610afead9284b9c65ee5ad9816ffcc0564243da is out of sync with the hash of contents {'inputs': [{'data_object_content': {'_class': 'FileContent', 'unnamed_file_content': {'_class': 'UnnamedFileContent', 'hash_value': u'd90bc4f01813690544e9d746c925f03d', 'hash_function': u'md5', '_id': u'9e6c22dcb2e9a6a69e28455982d589620e2e8a992524606cd6213c9a03401542'}, 'filename': u'chr22.fa', '_id': u'c59ef73bd87a5a742a6fec05a7b748eb018b62aeebb5da76fd760e28eefe0c08'}, '_class': 'TaskDefinitionInput', 'type': u'file', '_id': u'20bc2f9b08879451e2b42266d7af50148bd799f59730bf2ebabeb82a60b157bb'}], '_id': '4ee15f996ea3ae74f0515d54f610afead9284b9c65ee5ad9816ffcc0564243da', 'outputs': [{'_class': 'TaskDefinitionOutput', 'type': u'file', '_id': u'171c0ecb7d9aea1420aa92e0640811fe1321657d8a63dc83e581c2c90f8ee65e'}], 'environment': {'_class': 'TaskDefinitionDockerEnvironment', 'docker_image': u'isaacliao/bwa-0.7.7', '_id': '58a7284e14b375293a4c02b68095a4bb7544f43be35370f29d06126ad19dcc78'}, 'command': u'bwa index chr22.fa', '_class': 'TaskDefinition'} on model <class 'analysis.models.task_definitions.TaskDefinition'>"}

**Comment by nhammond** [comment]
Resolved since we dropped universalmodels
