### ISSUE TITLE
Support for CRCMOD32c file hash

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/loom#96]
Currently all our file hashes are with md5. Recommendations for hash methods are likely to change over time, and we need to make sure we have designed file hashing in a way that is extensible to support other formats.

Google Storage gives us our first chance for that -- they always provided CRCMOD32c hash but provide md5 only if parallel upload is not enabled.

**Comment by nhammond** [comment]
"loom import file" fails when the blob has a crcmod32c hash but not md5:

```
loom file import gs://genomics-public-data/resources/broad/hg38/v0/Homo_sapiens_assembly38.dbsnp138.vcf --link Calculating md5 on file "gs://genomics-public-data/resources/broad/hg38/v0/Homo_sapiens_assembly38.dbsnp138.vcf"... Traceback (most recent call last): File "/Library/Frameworks/Python.framework/Versions/2.7/bin/loom", line 11, in <module> load_entry_point('loomengine', 'console_scripts', 'loom')() File "/Users/s0198839/dev/loom/loom/client/loomengine/main.py", line 110, in main return Main().run() File "/Users/s0198839/dev/loom/loom/client/loomengine/main.py", line 106, in run return self.args.SubcommandClass(self.args).run() File "/Users/s0198839/dev/loom/loom/client/loomengine/file_client.py", line 396, in run self.args.SubSubcommandClass(self.args).run() File "/Users/s0198839/dev/loom/loom/client/loomengine/file_client.py", line 81, in run retry=self.args.retry File "/Users/s0198839/dev/loom/loom/utils/loomengine_utils/import_manager.py", line 107, in import_from_patterns retry=retry)) File "/Users/s0198839/dev/loom/loom/utils/loomengine_utils/import_manager.py", line 150, in import_file force_duplicates=force_duplicates, retry=retry) File "/Users/s0198839/dev/loom/loom/utils/loomengine_utils/import_manager.py", line 182, in _import_file_and_metadata source, comments, metadata=metadata, link=link) File "/Users/s0198839/dev/loom/loom/utils/loomengine_utils/import_manager.py", line 251, in _render_file_data_object_dict md5 = source.calculate_md5() File "/Users/s0198839/dev/loom/loom/utils/loomengine_utils/file_utils.py", line 446, in calculate_md5 md5_hex = md5_base64.decode('base64').encode('hex').strip() AttributeError: 'NoneType' object has no attribute 'decode'
```
